<Project>
  <PropertyGroup>
    <Configurations>Debug;LocalRun;Release</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'LocalRun'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(VCStartupProject)' == '$(MSBuildProjectName)' and '$(VCStartupOutputPath)' != ''">
    <OutputPath>$(VCStartupOutputPath)</OutputPath>
  </PropertyGroup>
</Project>
