using VirtualCompany.Domain.Enums;
namespace VirtualCompany.Domain.Entities;
public sealed class SalesPresentationRunArtifact:ICompanyOwnedEntity
{
    private SalesPresentationRunArtifact(){}
    public SalesPresentationRunArtifact(Guid id,Guid companyId,Guid runId,int preparationVersion,SalesPresentationRunArtifactType type,string content,string classification,string? sourceReference,Guid? presetSlideId,int order,Guid? aiRunId,DateTime createdUtc){if(companyId==Guid.Empty||runId==Guid.Empty)throw new ArgumentException("Company and run are required.");if(preparationVersion<1||order<0)throw new ArgumentOutOfRangeException(nameof(order));Id=id==Guid.Empty?Guid.NewGuid():id;CompanyId=companyId;RunId=runId;PreparationVersion=preparationVersion;Type=type;Content=Required(content,4000);Classification=Required(classification,32).ToLowerInvariant();SourceReference=Optional(sourceReference,500);PresetSlideId=presetSlideId;Order=order;AiRunId=aiRunId;CreatedUtc=createdUtc.Kind==DateTimeKind.Utc?createdUtc:createdUtc.ToUniversalTime();}
    public Guid Id{get;private set;} public Guid CompanyId{get;private set;} public Guid RunId{get;private set;} public int PreparationVersion{get;private set;} public SalesPresentationRunArtifactType Type{get;private set;} public string Content{get;private set;}=null!; public string Classification{get;private set;}=null!; public string? SourceReference{get;private set;} public Guid? PresetSlideId{get;private set;} public int Order{get;private set;} public Guid? AiRunId{get;private set;} public DateTime CreatedUtc{get;private set;} public SalesPresentationRun Run{get;private set;}=null!; public SalesPresentationPresetSlide? PresetSlide{get;private set;}
    private static string Required(string? value,int max){if(string.IsNullOrWhiteSpace(value))throw new ArgumentException("A value is required.");var v=value.Trim();if(v.Length>max)throw new ArgumentOutOfRangeException(nameof(value));return v;} private static string? Optional(string? value,int max)=>string.IsNullOrWhiteSpace(value)?null:Required(value,max);
}
