using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using VirtualCompany.Application.Auditing;
using VirtualCompany.Application.Sales;
using VirtualCompany.Domain.Entities;
using VirtualCompany.Domain.Enums;
using VirtualCompany.Infrastructure.Persistence;

namespace VirtualCompany.Infrastructure.Sales;

public sealed class SalesPresentationRunService(VirtualCompanyDbContext db,ISalesPresentationPresetService presets,TimeProvider timeProvider,ISalesMeetingSessionService sessions,ISalesNarrationService? narration=null):ISalesPresentationRunService
{
 public async Task<SalesPresentationRunDto?> GetActiveAsync(Guid companyId,Guid actor,Guid sessionId,CancellationToken ct){await Member(companyId,actor,ct);return await Map(companyId,sessionId,null,ct);}
 public async Task<SalesPresentationRunDto?> ApplyToInvitationAsync(Guid companyId,Guid actor,Guid invitationId,ApplySalesPresentationPresetCommand command,string? correlation,CancellationToken ct)
 {
  await Member(companyId,actor,ct);
  return await Execute(async () => {
   var existing=await db.SalesMeetingSessions.SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.InvitationId==invitationId,ct);
   if(existing is not null)return await ApplyCore(companyId,actor,existing.Id,command,correlation,ct);
   var version=command.PresetVersionId.HasValue?await Published(companyId,command.PresetVersionId.Value,ct):null;
   if(version is null||version.Preset.Lifecycle==SalesPresentationPresetLifecycle.Archived||!version.AllowSalesMeeting||version.Asset?.Status!=SalesPresentationPresetAssetStatus.Processed||version.Asset.Slides.Count==0)
    throw Conflict(SalesPresentationRunProblemCodes.NotReady,"Choose a published, processed sales meeting preset.");
   var created=await sessions.CreateOrUpdateAsync(companyId,actor,invitationId,new(Value(command.Goal,null,version.Goal),Value(command.Audience,null,version.Audience),command.DurationMinutes??version.DurationMinutes,command.DemoScenario??version.DemoScenario,"not_requested",PresetRetention(version)==365?"standard":"custom",PresetRetention(version)),correlation,ct);
   return await ApplyCore(companyId,actor,created.Id,command,correlation,ct);
  },ct);
 }
 public Task<SalesPresentationRunDto?> ApplyAsync(Guid companyId,Guid actor,Guid sessionId,ApplySalesPresentationPresetCommand command,string? correlation,CancellationToken ct)
  => Execute(()=>ApplyCore(companyId,actor,sessionId,command,correlation,ct),ct);
 private async Task<SalesPresentationRunDto?> Execute(Func<Task<SalesPresentationRunDto?>> action,CancellationToken ct)
 {
  if(db.Database.CurrentTransaction is not null)return await action();
  return await db.Database.CreateExecutionStrategy().ExecuteAsync(async () => {
   await using var transaction=await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable,ct);
   try {var result=await action();await transaction.CommitAsync(ct);return result;}
   catch {await transaction.RollbackAsync(ct);db.ChangeTracker.Clear();throw;}
  });
 }
 private static int PresetRetention(SalesPresentationPresetVersion version)
 {
  using var document=JsonDocument.Parse(version.BehaviorSettingsJson??"{}");
  return document.RootElement.TryGetProperty("retentionDays",out var value)&&value.ValueKind==JsonValueKind.Number&&value.TryGetInt32(out var days)&&days is >=1 and <=3650?days:365;
 }
 private async Task<SalesPresentationRunDto?> ApplyCore(Guid companyId,Guid actor,Guid sessionId,ApplySalesPresentationPresetCommand command,string? correlation,CancellationToken ct)
 {
  await Member(companyId,actor,ct);var session=await db.SalesMeetingSessions.SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.Id==sessionId,ct);if(session is null)return null;
  if(session.CreatedByUserId!=actor)throw new UnauthorizedAccessException("Only the meeting organizer can apply a presentation preset.");
  var version=command.PresetVersionId.HasValue?await Published(companyId,command.PresetVersionId.Value,ct):command.PresetId.HasValue?await db.SalesPresentationPresetVersions.Include(x=>x.Preset).Include(x=>x.Asset).ThenInclude(x=>x!.Slides).SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.PresetId==command.PresetId&&x.Preset.CurrentPublishedVersionId==x.Id&&x.Lifecycle==SalesPresentationPresetVersionLifecycle.Published,ct):null;
  if(version is null||version.Preset.Lifecycle==SalesPresentationPresetLifecycle.Archived||!version.AllowSalesMeeting||version.Asset?.Status!=SalesPresentationPresetAssetStatus.Processed||version.Asset.Slides.Count==0)throw Conflict(SalesPresentationPresetProblemCodes.NotReady,"Choose an available, processed preset version that supports sales meetings.");
  var current=await db.SalesPresentationRuns.SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.MeetingSessionId==sessionId&&x.IsActive,ct);
  // Reusing the pinned version is a read-only replay, even after the meeting starts.
  if(current?.PresetVersionId==version.Id)return await Map(companyId,sessionId,current.Id,ct);
  if(!await SalesMeetingPresetEligibility.CanChangeAsync(db,session,ct))throw Conflict(SalesPresentationRunProblemCodes.NotReady,
   session.Status is SalesMeetingSessionStatus.Completed or SalesMeetingSessionStatus.Cancelled or SalesMeetingSessionStatus.Failed
    ? "This meeting has ended. Its presentation history cannot be changed. Schedule a new meeting to use this preset."
    : "Leave the meeting room and stop the agent before changing its presentation preset.");
  if(current is not null){if(current.PresetVersionId==version.Id)return await Map(companyId,sessionId,current.Id,ct);if(!command.ReplaceActive)throw Conflict(SalesPresentationRunProblemCodes.ActiveRunExists,"This meeting already has a pinned presentation run. Review the version changes before replacing it.");if(command.ExpectedActiveRunVersion!=current.ConcurrencyVersion)throw Conflict(SalesPresentationRunProblemCodes.Conflict,"The presentation run changed. Refresh and review it again.");current.Deactivate(actor,Now());var oldDeck=current.CompatibilityDeckId.HasValue?await db.SalesPresentationDecks.SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.Id==current.CompatibilityDeckId,ct):null;if(oldDeck?.IsActive==true)oldDeck.Deactivate(Now());}
  var presenterId=command.PresenterAgentId??version.DefaultPresenterAgentId??session.PresenterAgentId??throw Conflict(SalesPresentationRunProblemCodes.InvalidPresenter,"Choose an active Sales presenter.");var presenter=await db.Agents.SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.Id==presenterId,ct);if(presenter is null||!presenter.CanReceiveAssignments||!string.Equals(presenter.Department,"Sales",StringComparison.OrdinalIgnoreCase))throw Conflict(SalesPresentationRunProblemCodes.InvalidPresenter,"The selected presenter is inactive or lacks the Sales presenter capability.");
  var goal=Value(command.Goal,current?.GoalOverridden==true?current.Goal:null,version.Goal);var audience=Value(command.Audience,current?.AudienceOverridden==true?current.Audience:null,version.Audience);var duration=command.DurationMinutes??(current?.DurationOverridden==true?current.DurationMinutes:version.DurationMinutes);var demo=command.DemoScenario??(current?.DemoScenarioOverridden==true?current.DemoScenario:version.DemoScenario);var language=Value(command.Language,null,version.Language);var mode=Value(command.ControlMode,null,version.ControlMode);
  session.ReopenPreparation(actor,Now());
  session.UpdatePreparation(goal,audience,duration,demo,session.ConsentStatus,PresetRetention(version)==365?SalesMeetingRetentionPolicy.Standard:SalesMeetingRetentionPolicy.Custom,PresetRetention(version),actor,Now());
  session.SelectPresenter(presenterId,actor,Now());
  session.SetPresentationControlMode(mode,session.ConcurrencyVersion,actor,Now());
  // Release the unique active-deck slot before inserting a preset-backed deck.
  // Execute keeps both writes atomic, including replacement of a legacy upload.
  var activeDecks=await db.SalesPresentationDecks.Where(x=>x.CompanyId==companyId&&x.SessionId==sessionId&&x.IsActive).ToListAsync(ct);
  foreach(var activeDeck in activeDecks)activeDeck.Deactivate(Now());
  await Save(ct);
  var run=new SalesPresentationRun(Guid.NewGuid(),companyId,version.Id,sessionId,presenterId,goal,audience,duration,demo,language,mode,!Same(goal,version.Goal),!Same(audience,version.Audience),duration!=version.DurationMinutes,!Same(demo,version.DemoScenario),presenterId!=version.DefaultPresenterAgentId,actor,Now());run.BeginPreparation(actor,Now());
  var deckVersion=(await db.SalesPresentationDecks.Where(x=>x.CompanyId==companyId&&x.SessionId==sessionId).MaxAsync(x=>(int?)x.Version,ct)??0)+1;var asset=version.Asset!;var deck=new SalesPresentationDeck(Guid.NewGuid(),companyId,sessionId,presenterId,deckVersion,version.Preset.Name,asset.OriginalFileName,asset.ContentType,asset.FileSizeBytes,asset.ContentHash,asset.StorageKey,asset.StorageUrl,actor,Now());deck.BindToPresentationRun(run.Id,asset.Id);deck.BeginProcessing(Now(),TimeSpan.Zero);
  var slides=asset.Slides.OrderBy(x=>x.SlideNumber).Select(x=>new SalesPresentationSlide(Guid.NewGuid(),companyId,deck.Id,asset.ProcessingVersion,x.SlideNumber,x.Title,x.ExtractedText,x.SpeakerNotes,x.ImageStorageKey,x.ImageStorageUrl,x.ImageWidthPixels,x.ImageHeightPixels,x.SourceWidthEmus,x.SourceHeightEmus,x.ContentHash,x.Objective,x.ExpectedDurationSeconds,x.TransitionText,Now())).ToArray();deck.MarkProcessed(slides.Length,asset.RendererName??"preset",asset.RendererVersion??asset.ProcessingVersion.ToString(),asset.AnimationHandling??"preserved where supported",1,Now());deck.Activate(Now());
  foreach(var slide in slides)
  {
   var source=asset.Slides.Single(x=>x.SlideNumber==slide.SlideNumber);
   var content=string.IsNullOrWhiteSpace(source.BaselineTalkingPoints)?source.Objective:source.BaselineTalkingPoints;
   var points=content.Chunk(4000).Select(x=>new string(x)).Where(x=>!string.IsNullOrWhiteSpace(x)).ToArray();
   for(var index=0;index<points.Length;index++)
    db.SalesMeetingArtifacts.Add(new SalesMeetingArtifact(Guid.NewGuid(),companyId,sessionId,deck.Id,slide.Id,asset.ProcessingVersion,SalesMeetingArtifactType.SlideTalkingPoint,"talking_points",index,points[index],SalesMeetingArtifactClassification.Recommendation,$"preset-slide:{source.Id:D}",null,Now()));
  }
  var artifacts=Ground(run,session,version,actor);var blockers=new List<string>();if(session.ContactId is null)blockers.Add("contact_context_missing");if(session.DealId is null)blockers.Add("deal_context_missing");run.CompletePreparation(deck.Id,blockers.Count>0,blockers.Count==0?null:JsonSerializer.Serialize(blockers),actor,Now());db.Add(run);db.Add(deck);db.AddRange(slides);db.AddRange(artifacts);Audit(companyId,actor,"sales.presentation_run.applied",run.Id,sessionId,version.Id,"An immutable presentation preset version was applied and materialized as a compatibility deck.",correlation);await Save(ct);if(narration is not null)await narration.BindPresetAsync(companyId,actor,version.Id,sessionId,deck.Id,ct);return await Map(companyId,sessionId,run.Id,ct);
 }
 public async Task<SalesPresentationRunDto?> RetryAsync(Guid companyId,Guid actor,Guid sessionId,Guid runId,long expected,string? correlation,CancellationToken ct){await Member(companyId,actor,ct);var run=await db.SalesPresentationRuns.SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.Id==runId&&x.MeetingSessionId==sessionId&&x.IsActive,ct);if(run is null)return null;if(run.ConcurrencyVersion!=expected)throw Conflict(SalesPresentationRunProblemCodes.Conflict,"The presentation run changed.");run.QueueRetry(actor,Now());Audit(companyId,actor,"sales.presentation_run.retry_queued",run.Id,sessionId,run.PresetVersionId,"Presentation preparation was queued for retry.",correlation);await Save(ct);return await Map(companyId,sessionId,runId,ct);}
 public async Task<SalesPresentationRunVersionComparisonDto?> CompareVersionAsync(Guid companyId,Guid actor,Guid sessionId,Guid runId,Guid targetId,CancellationToken ct){await Member(companyId,actor,ct);var run=await db.SalesPresentationRuns.Include(x=>x.PresetVersion).SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.Id==runId&&x.MeetingSessionId==sessionId&&x.IsActive,ct);if(run is null)return null;var target=await Published(companyId,targetId,ct);if(target is null||target.PresetId!=run.PresetVersion.PresetId)return null;var changes=new List<SalesPresentationRunVersionChangeDto>();Add(changes,"Goal",run.PresetVersion.Goal,target.Goal,run.GoalOverridden);Add(changes,"Audience",run.PresetVersion.Audience,target.Audience,run.AudienceOverridden);Add(changes,"Duration",run.PresetVersion.DurationMinutes.ToString(),target.DurationMinutes.ToString(),run.DurationOverridden);Add(changes,"Demo scenario",run.PresetVersion.DemoScenario??"None",target.DemoScenario??"None",run.DemoScenarioOverridden);Add(changes,"Control mode",run.PresetVersion.ControlMode,target.ControlMode,false);return new(run.Id,run.PresetVersionId,run.PresetVersion.VersionNumber,target.Id,target.VersionNumber,changes,true,[]);}
 public async Task<SalesPresentationPresetDto?> SaveAsPresetAsync(Guid companyId,Guid actor,Guid sessionId,Guid deckId,string name,string? description,string? correlation,CancellationToken ct){await Member(companyId,actor,ct);var session=await db.SalesMeetingSessions.SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.Id==sessionId,ct);var deck=await db.SalesPresentationDecks.SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.SessionId==sessionId&&x.Id==deckId&&x.Status==SalesPresentationDeckStatus.Processed,ct);if(session is null||deck is null)return null;if(session.CreatedByUserId!=actor)throw new UnauthorizedAccessException("Only the meeting organizer can save this setup as a preset.");var sourceSlides=await db.SalesPresentationSlides.AsNoTracking().Where(x=>x.CompanyId==companyId&&x.DeckId==deckId).OrderBy(x=>x.SlideNumber).ToListAsync(ct);if(sourceSlides.Count==0)throw Conflict(SalesPresentationPresetProblemCodes.NotReady,"The meeting deck has no reusable processed slides.");var created=await presets.CreateAsync(companyId,actor,new(name,description,actor,deck.AgentId,session.MeetingGoal,session.IntendedAudience,session.PlannedDurationMinutes,session.DemoScenario,session.PresentationControlMode,"en",["sales_meeting"],null,null),correlation,ct);var draft=created.CurrentDraft!;var asset=new SalesPresentationPresetAsset(Guid.NewGuid(),companyId,draft.Id,deck.OriginalFileName,deck.ContentType,deck.FileSizeBytes,deck.ContentHash,deck.StorageKey,deck.StorageUrl,actor,Now());asset.BeginProcessing(Now(),TimeSpan.Zero);var reusable=sourceSlides.Select(x=>new SalesPresentationPresetSlide(Guid.NewGuid(),companyId,asset.Id,asset.ProcessingVersion,x.SlideNumber,x.Title,x.ExtractedText,x.SpeakerNotes,x.ImageStorageKey,x.ImageStorageUrl,x.ImageWidthPixels,x.ImageHeightPixels,x.SourceWidthEmus,x.SourceHeightEmus,x.ContentHash,x.Objective,string.IsNullOrWhiteSpace(x.ExtractedText)?x.Objective:x.ExtractedText,x.ExpectedDurationSeconds,x.TransitionText,Now())).ToArray();asset.MarkProcessed(reusable.Length,deck.RendererName??"legacy",deck.RendererVersion??"1",deck.AnimationHandling??"preserved where supported",Now());db.Add(asset);db.AddRange(reusable);Audit(companyId,actor,"sales.presentation_run.saved_as_preset",deck.PresentationRunId??deck.Id,sessionId,draft.Id,"Reusable source references, rendered slides, and generic configuration were copied; customer and runtime evidence was excluded.",correlation);await Save(ct);return await presets.GetAsync(companyId,actor,created.Id,ct);}
 private async Task<SalesPresentationPresetVersion?> Published(Guid companyId,Guid id,CancellationToken ct)=>await db.SalesPresentationPresetVersions.Include(x=>x.Preset).Include(x=>x.Asset).ThenInclude(x=>x!.Slides).SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.Id==id&&x.Lifecycle==SalesPresentationPresetVersionLifecycle.Published,ct);
 private List<SalesPresentationRunArtifact> Ground(SalesPresentationRun run,SalesMeetingSession session,SalesPresentationPresetVersion version,Guid actor){var now=Now();var list=new List<SalesPresentationRunArtifact>{A(SalesPresentationRunArtifactType.ConfirmedFact,$"Meeting goal: {run.Goal}","internal",$"sales_meeting_session:{session.Id:D}",0),A(SalesPresentationRunArtifactType.ConfirmedFact,$"Lead: {session.LeadId:D}","internal",$"lead:{session.LeadId:D}",1),A(SalesPresentationRunArtifactType.Positioning,$"Present {version.Preset.Name} for {run.Audience}.","internal",$"preset_version:{version.Id:D}",2)};if(session.DealId is Guid deal)list.Add(A(SalesPresentationRunArtifactType.ConfirmedFact,$"Deal context: {deal:D}","internal",$"deal:{deal:D}",3));else list.Add(A(SalesPresentationRunArtifactType.MissingEvidence,"No deal is linked; review commercial claims before presenting.","needs_review",null,3));if(session.ContactId is Guid contact)list.Add(A(SalesPresentationRunArtifactType.ConfirmedFact,$"Primary contact: {contact:D}","internal",$"contact:{contact:D}",4));else list.Add(A(SalesPresentationRunArtifactType.MissingEvidence,"No contact is linked; confirm the attendee context before presenting.","needs_review",null,4));return list;SalesPresentationRunArtifact A(SalesPresentationRunArtifactType type,string content,string classification,string? source,int order)=>new(Guid.NewGuid(),run.CompanyId,run.Id,run.PreparationVersion,type,content,classification,source,null,order,null,now);}
 private async Task<SalesPresentationRunDto?> Map(Guid companyId,Guid sessionId,Guid? id,CancellationToken ct){var q=db.SalesPresentationRuns.AsNoTracking().Include(x=>x.PresetVersion).ThenInclude(x=>x.Preset).Include(x=>x.PresenterAgent).Include(x=>x.Artifacts).Where(x=>x.CompanyId==companyId&&x.MeetingSessionId==sessionId);var r=id.HasValue?await q.SingleOrDefaultAsync(x=>x.Id==id,ct):await q.SingleOrDefaultAsync(x=>x.IsActive,ct);if(r is null)return null;var latest=await db.SalesPresentationPresetVersions.AsNoTracking().Where(x=>x.CompanyId==companyId&&x.PresetId==r.PresetVersion.PresetId&&x.Lifecycle==SalesPresentationPresetVersionLifecycle.Published).MaxAsync(x=>(int?)x.VersionNumber,ct);return new(r.Id,sessionId,r.PresetVersion.PresetId,r.PresetVersion.Preset.Name,r.PresetVersionId,r.PresetVersion.VersionNumber,r.PresenterAgentId,r.PresenterAgent.DisplayName,r.Goal,r.Audience,r.DurationMinutes,r.DemoScenario,r.Language,r.ControlMode,r.GoalOverridden,r.AudienceOverridden,r.DurationOverridden,r.DemoScenarioOverridden,r.PresenterOverridden,r.PreparationStatus.ToStorageValue(),Parse(r.ReadinessBlockersJson),r.CanRetry,r.FailureCode,r.FailureSummary,r.CompatibilityDeckId,r.IsActive,latest>r.PresetVersion.VersionNumber?latest:null,r.ConcurrencyVersion,r.Artifacts.OrderBy(x=>x.Order).Select(x=>new SalesPresentationRunArtifactDto(x.Id,x.Type.ToStorageValue(),x.Content,x.Classification,x.SourceReference,x.PresetSlideId,x.Order,x.AiRunId)).ToArray());}
 private async Task Member(Guid companyId,Guid actor,CancellationToken ct){if(companyId==Guid.Empty||actor==Guid.Empty||!await db.CompanyMemberships.AsNoTracking().AnyAsync(x=>x.CompanyId==companyId&&x.UserId==actor&&x.Status==CompanyMembershipStatus.Active,ct))throw new UnauthorizedAccessException("An active company membership is required.");}
 private void Audit(Guid company,Guid actor,string action,Guid run,Guid session,Guid version,string rationale,string? correlation)=>db.AuditEvents.Add(new AuditEvent(Guid.NewGuid(),company,AuditActorTypes.User,actor,action,"sales_presentation_run",run.ToString("D"),AuditEventOutcomes.Succeeded,rationale,["presentation run"],new Dictionary<string,string?>{{"runId",run.ToString("D")},{"sessionId",session.ToString("D")},{"presetVersionId",version.ToString("D")}},correlation,Now()));
 private async Task Save(CancellationToken ct){try{await db.SaveChangesAsync(ct);}catch(DbUpdateConcurrencyException){throw Conflict(SalesPresentationRunProblemCodes.Conflict,"The presentation run changed concurrently. Refresh and try again.");}}
 private static void Add(List<SalesPresentationRunVersionChangeDto> c,string field,string oldValue,string newValue,bool preserve){if(!Same(oldValue,newValue))c.Add(new(field,oldValue,newValue,preserve,false));}private static bool Same(string? a,string? b)=>string.Equals(a?.Trim(),b?.Trim(),StringComparison.Ordinal);private static string Value(string? first,string? second,string fallback)=>!string.IsNullOrWhiteSpace(first)?first.Trim():!string.IsNullOrWhiteSpace(second)?second.Trim():fallback;private static IReadOnlyList<string> Parse(string? json){if(string.IsNullOrWhiteSpace(json))return[];try{return JsonSerializer.Deserialize<string[]>(json)??[];}catch(JsonException){return["readiness_evidence_invalid"];}}private static SalesPresentationPresetConflictException Conflict(string code,string message)=>new(code,message);private DateTime Now()=>timeProvider.GetUtcNow().UtcDateTime;
}
