using System.Text.Json.Nodes;
using VirtualCompany.Application.Agents;
using VirtualCompany.Application.GuidedWork;
using VirtualCompany.Application.Sales;

namespace VirtualCompany.Infrastructure.Sales;

public sealed class SalesCampaignGuidedArtifactDefinition(ICampaignPlanningService planning, IOutboundCampaignService campaigns, IAgentCapabilityCatalog capabilities) : IGuidedArtifactDefinition
{
    public string ArtifactType=>GuidedArtifactTypes.SalesCampaignPlan; public string SchemaVersion=>"1.0"; public string DisplayName=>"Sales campaign plan";
    public bool RequiresTargetArtifact=>true;
    public IReadOnlyList<string> QuestionPriorities=>["objective_type","objective_target","audience_segment_id","offer_name","planning_starts","scheduled_launch","ends","activities","planned_budget"];
    public IReadOnlyList<GuidedFieldDefinition> Fields {get;}=
    [
        T("campaign_type","Campaign type",true,64),T("description","Description",true),T("objective_type","Objective type",true,64),N("objective_target","Objective target",true),T("objective_unit","Objective unit",true,64),D("objective_target_date","Objective target date",true),
        D("planning_starts","Planning starts",true),D("scheduled_launch","Scheduled launch",true),D("ends","Campaign ends",true),T("time_zone","Time zone",true,128),N("planned_budget","Planned budget"),T("budget_currency","Budget currency",false,3),D("review_due","Review due"),
        T("offer_name","Offer name",true,200),T("offer_source_type","Offer source type",true,64),T("offer_source_reference","Offer source reference",true,500),I("offer_knowledge_document_id","Offer knowledge document"),B("no_offer_required","No offer required"),
        I("audience_segment_id","Audience segment",true),O("activities","Activities and cadence")
    ];
    public async Task EnsureEligibleAsync(Guid c,Guid a,CancellationToken ct){var catalog=await capabilities.GetEffectiveCatalogAsync(c,a,ct);var cap=catalog.Capabilities.SingleOrDefault(x=>x.Id==AgentCapabilityIds.SalesCampaignOptimization);if(cap is null||cap.State is AgentCapabilityStates.PermissionDenied or AgentCapabilityStates.NotImplemented)throw new GuidedArtifactNotEligibleException("The selected agent does not have the tools and data permissions required for Sales campaign workshops.");}
    public async Task<GuidedArtifactInitialization> InitializeAsync(Guid companyId,Guid agentId,Guid? targetId,CancellationToken ct)
    {
        if(targetId is not Guid id)throw new GuidedWorkValidationException(new Dictionary<string,string[]>{{nameof(targetId),["Choose an existing Sales campaign before starting this workshop."]}});
        var campaign=await campaigns.GetCampaignAsync(companyId,id,ct)??throw new KeyNotFoundException("Sales campaign not found.");
        var current=await planning.GetInitiativeAsync(companyId,id,ct);var v=new Dictionary<string,JsonNode?>(StringComparer.OrdinalIgnoreCase){{"description",campaign.Description??""},{"time_zone","UTC"}};
        if(current is not null){v["campaign_type"]=current.CampaignType;v["description"]=current.Description??"";if(current.PrimaryObjective is { } o){v["objective_type"]=o.Type;v["objective_target"]=o.Target;v["objective_unit"]=o.Unit;v["objective_target_date"]=o.TargetUtc.ToString("yyyy-MM-dd");}v["planning_starts"]=current.PlanningStartsUtc?.ToString("yyyy-MM-dd");v["scheduled_launch"]=current.ScheduledLaunchUtc?.ToString("yyyy-MM-dd");v["ends"]=current.EndsUtc?.ToString("yyyy-MM-dd");v["time_zone"]=current.TimeZoneId;v["planned_budget"]=current.PlannedBudget;v["budget_currency"]=current.BudgetCurrency;v["review_due"]=current.ReviewDueUtc?.ToString("yyyy-MM-dd");}
        return new(DisplayName,id,(current?.Version??0).ToString(),v,OpeningSummary:$"Plan the objective, audience, offer, schedule, budget, and activities for {campaign.Name}.",OpeningQuestion:"What measurable outcome should this campaign achieve, and by when?");
    }
    public async Task<IReadOnlyList<string>> ValidateAsync(Guid c,Guid a,Guid? target,IReadOnlyDictionary<string,JsonNode?> v,CancellationToken ct)
    {
        var gaps=Fields.Where(x=>x.IsRequired&&(!v.TryGetValue(x.Path,out var n)||n is null||string.IsNullOrWhiteSpace(n.ToString()))).Select(x=>x.Label).ToList();
        if(Date(v,"scheduled_launch")<Date(v,"planning_starts"))gaps.Add("Scheduled launch must follow planning start");if(Date(v,"ends")<=Date(v,"scheduled_launch"))gaps.Add("Campaign end must follow launch");
        if(Guid.TryParse(Text(v,"audience_segment_id"),out var segment)&&!(await planning.ListSegmentsAsync(c,ct)).Any(x=>x.Id==segment&&x.IsActive))gaps.Add("Audience segment must be active in this company");return gaps;
    }
    public Task<IReadOnlyList<GuidedReviewInsightDto>> BuildReviewInsightsAsync(Guid c,Guid a,Guid? t,IReadOnlyDictionary<string,JsonNode?>v,CancellationToken ct)=>Task.FromResult<IReadOnlyList<GuidedReviewInsightDto>>([new("Schedule",$"{Text(v,"scheduled_launch")} to {Text(v,"ends")}","Activity dates and readiness remain subject to the campaign planning service."),new("Planned budget",string.IsNullOrWhiteSpace(Text(v,"planned_budget"))?"Not set":$"{Text(v,"planned_budget")} {Text(v,"budget_currency")}","This is planning context and does not authorize provider spend."),new("Confirmation effect","Save campaign plan only","Confirmation does not launch, send, publish, acquire contacts, schedule meetings, or enqueue outbound delivery.")]);
    public async Task<GuidedArtifactCommitResult> CommitAsync(GuidedArtifactCommitContext c,CancellationToken ct)
    {
        if(c.TargetArtifactId is not Guid campaignId)throw new GuidedWorkConflictException("An existing Sales campaign is required.");var expected=long.TryParse(c.TargetArtifactVersion,out var e)?e:0;
        var request=new ConfigureCampaignInitiativeRequest(Text(c.Values,"campaign_type"),Text(c.Values,"description"),c.UserId,c.AgentId,Text(c.Values,"objective_type"),Dec(c.Values,"objective_target"),Text(c.Values,"objective_unit"),Date(c.Values,"objective_target_date"),Date(c.Values,"planning_starts"),Date(c.Values,"scheduled_launch"),Date(c.Values,"ends"),Text(c.Values,"time_zone"),NullableDec(c.Values,"planned_budget"),NullText(c.Values,"budget_currency"),NullableDate(c.Values,"review_due"),expected,new(Text(c.Values,"offer_name"),Text(c.Values,"offer_source_type"),Text(c.Values,"offer_source_reference"),Guid.TryParse(Text(c.Values,"offer_knowledge_document_id"),out var doc)?doc:null,Bool(c.Values,"no_offer_required")));
        var result=await planning.ConfigureInitiativeAsync(c.CompanyId,c.UserId,campaignId,request,ct)??throw new GuidedWorkConflictException("The Sales campaign changed or is unavailable.");
        if(Guid.TryParse(Text(c.Values,"audience_segment_id"),out var segment))await planning.CaptureAudienceAsync(c.CompanyId,c.UserId,campaignId,segment,ct);
        if(c.Values.TryGetValue("activities",out var node)&&node is JsonObject activityObject&&activityObject["items"] is JsonArray activities)foreach(var item in activities.OfType<JsonObject>()){var name=item["name"]?.GetValue<string>();if(string.IsNullOrWhiteSpace(name))continue;await planning.AddActivityAsync(c.CompanyId,c.UserId,campaignId,new(name,item["activityType"]?.GetValue<string>()??"outreach",item["channel"]?.GetValue<string>()??"email",item["executionMode"]?.GetValue<string>()??"manual",ParseDate(item["plannedStart"],result.PlanningStartsUtc??DateTime.UtcNow),ParseDate(item["due"],result.ScheduledLaunchUtc??DateTime.UtcNow.AddDays(7)),result.TimeZoneId,c.UserId,c.AgentId,null,null,null,null),ct);}
        return new(result.Id,result.Version.ToString(),$"Saved the campaign plan with lifecycle status {result.LifecycleStatus}.");
    }
    private static GuidedFieldDefinition T(string p,string l,bool r=false,int max=8000)=>new(p,l,$"Set {l.ToLowerInvariant()}.",GuidedFieldValueTypes.Text,r,MaxLength:max,AllowsEvidence:true);private static GuidedFieldDefinition N(string p,string l,bool r=false)=>new(p,l,$"Set {l.ToLowerInvariant()}.",GuidedFieldValueTypes.Number,r);private static GuidedFieldDefinition D(string p,string l,bool r=false)=>new(p,l,$"Set {l.ToLowerInvariant()}.",GuidedFieldValueTypes.Date,r);private static GuidedFieldDefinition I(string p,string l,bool r=false)=>new(p,l,$"Select {l.ToLowerInvariant()}.",GuidedFieldValueTypes.Identifier,r);private static GuidedFieldDefinition B(string p,string l)=>new(p,l,$"Set {l.ToLowerInvariant()}.",GuidedFieldValueTypes.Boolean,false);private static GuidedFieldDefinition O(string p,string l)=>new(p,l,$"Define {l.ToLowerInvariant()} as structured items.",GuidedFieldValueTypes.Object,false);
    private static string Text(IReadOnlyDictionary<string,JsonNode?>v,string k)=>v.TryGetValue(k,out var n)?n?.ToString().Trim('"')??"":"";private static string? NullText(IReadOnlyDictionary<string,JsonNode?>v,string k)=>string.IsNullOrWhiteSpace(Text(v,k))?null:Text(v,k);private static decimal Dec(IReadOnlyDictionary<string,JsonNode?>v,string k)=>decimal.Parse(v[k]!.ToString());private static decimal? NullableDec(IReadOnlyDictionary<string,JsonNode?>v,string k)=>v.TryGetValue(k,out var n)&&decimal.TryParse(n?.ToString(),out var d)?d:null;private static DateTime Date(IReadOnlyDictionary<string,JsonNode?>v,string k)=>DateTime.SpecifyKind(DateTime.Parse(Text(v,k)),DateTimeKind.Utc);private static DateTime? NullableDate(IReadOnlyDictionary<string,JsonNode?>v,string k)=>DateTime.TryParse(Text(v,k),out var d)?DateTime.SpecifyKind(d,DateTimeKind.Utc):null;private static bool Bool(IReadOnlyDictionary<string,JsonNode?>v,string k)=>v.TryGetValue(k,out var n)&&bool.TryParse(n?.ToString(),out var b)&&b;private static DateTime ParseDate(JsonNode? n,DateTime fallback)=>DateTime.TryParse(n?.GetValue<string>(),out var d)?DateTime.SpecifyKind(d,DateTimeKind.Utc):fallback;
}
