using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
namespace VirtualCompany.Infrastructure.Persistence.Migrations;

public partial class AddSalesSourceAttribution : Migration
{
    protected override void Up(MigrationBuilder m)
    {
        m.CreateTable("SalesAcquisitionCampaigns", columns: t => new { Id=t.Column<Guid>("uniqueidentifier"), CompanyId=t.Column<Guid>("uniqueidentifier"), Name=t.Column<string>("nvarchar(200)",maxLength:200), Category=t.Column<string>("nvarchar(64)",maxLength:64), Provider=t.Column<string>("nvarchar(120)",maxLength:120), ExternalReference=t.Column<string>("nvarchar(256)",maxLength:256,nullable:true), Budget=t.Column<decimal>("decimal(18,2)",nullable:true), Currency=t.Column<string>("nvarchar(3)",maxLength:3,nullable:true), StartsUtc=t.Column<DateTime>("datetime2",nullable:true), EndsUtc=t.Column<DateTime>("datetime2",nullable:true), Status=t.Column<string>("nvarchar(32)",maxLength:32), CreatedUtc=t.Column<DateTime>("datetime2"), UpdatedUtc=t.Column<DateTime>("datetime2") }, constraints: c=>c.PrimaryKey("PK_SalesAcquisitionCampaigns",x=>x.Id));
        m.CreateTable("SalesContactPermissions", columns: t => new { Id=t.Column<Guid>("uniqueidentifier"), CompanyId=t.Column<Guid>("uniqueidentifier"), ContactId=t.Column<Guid>("uniqueidentifier"), Channel=t.Column<string>("nvarchar(32)",maxLength:32), Address=t.Column<string>("nvarchar(320)",maxLength:320), Status=t.Column<string>("nvarchar(32)",maxLength:32), LegalBasis=t.Column<string>("nvarchar(64)",maxLength:64), SourceReference=t.Column<string>("nvarchar(512)",maxLength:512), ObservedUtc=t.Column<DateTime>("datetime2"), CreatedUtc=t.Column<DateTime>("datetime2"), UpdatedUtc=t.Column<DateTime>("datetime2") },constraints: c=>c.PrimaryKey("PK_SalesContactPermissions",x=>x.Id));
        m.CreateTable("SalesSourceAttributions", columns: t => new { Id=t.Column<Guid>("uniqueidentifier"), CompanyId=t.Column<Guid>("uniqueidentifier"), SubjectType=t.Column<string>("nvarchar(40)",maxLength:40), SubjectId=t.Column<Guid>("uniqueidentifier"), OriginalTouchId=t.Column<Guid>("uniqueidentifier"), FirstTouchId=t.Column<Guid>("uniqueidentifier"), LastTouchId=t.Column<Guid>("uniqueidentifier"), ConversionTouchId=t.Column<Guid>("uniqueidentifier",nullable:true), TouchCount=t.Column<int>("int"), TotalAcquisitionCost=t.Column<decimal>("decimal(18,2)"), Currency=t.Column<string>("nvarchar(3)",maxLength:3,nullable:true), CreatedUtc=t.Column<DateTime>("datetime2"), UpdatedUtc=t.Column<DateTime>("datetime2") },constraints: c=>c.PrimaryKey("PK_SalesSourceAttributions",x=>x.Id));
        m.CreateTable("SalesSourceTouches", columns: t => new { Id=t.Column<Guid>("uniqueidentifier"), CompanyId=t.Column<Guid>("uniqueidentifier"), CampaignId=t.Column<Guid>("uniqueidentifier",nullable:true), SubjectType=t.Column<string>("nvarchar(40)",maxLength:40), SubjectId=t.Column<Guid>("uniqueidentifier"), Category=t.Column<string>("nvarchar(64)",maxLength:64), Provider=t.Column<string>("nvarchar(120)",maxLength:120), Channel=t.Column<string>("nvarchar(64)",maxLength:64), InteractionType=t.Column<string>("nvarchar(64)",maxLength:64), SourceReference=t.Column<string>("nvarchar(512)",maxLength:512), Evidence=t.Column<string>("nvarchar(1000)",maxLength:1000,nullable:true), LandingPage=t.Column<string>("nvarchar(512)",maxLength:512,nullable:true), Referrer=t.Column<string>("nvarchar(512)",maxLength:512,nullable:true), UtmSource=t.Column<string>("nvarchar(120)",maxLength:120,nullable:true), UtmMedium=t.Column<string>("nvarchar(120)",maxLength:120,nullable:true), UtmCampaign=t.Column<string>("nvarchar(200)",maxLength:200,nullable:true), UtmContent=t.Column<string>("nvarchar(200)",maxLength:200,nullable:true), UtmTerm=t.Column<string>("nvarchar(200)",maxLength:200,nullable:true), Cost=t.Column<decimal>("decimal(18,2)",nullable:true), Currency=t.Column<string>("nvarchar(3)",maxLength:3,nullable:true), ActorType=t.Column<string>("nvarchar(32)",maxLength:32), ActorReference=t.Column<string>("nvarchar(160)",maxLength:160,nullable:true), MetadataJson=t.Column<string>("nvarchar(max)",maxLength:8000,nullable:true), DedupeKey=t.Column<string>("nvarchar(1000)",maxLength:1000), ObservedUtc=t.Column<DateTime>("datetime2"), CreatedUtc=t.Column<DateTime>("datetime2") },constraints: c=>{c.PrimaryKey("PK_SalesSourceTouches",x=>x.Id);c.ForeignKey("FK_SalesSourceTouches_SalesAcquisitionCampaigns_CampaignId",x=>x.CampaignId,"SalesAcquisitionCampaigns","Id",onDelete:ReferentialAction.SetNull);});
        m.AlterColumn<string>(name: "DedupeKey", table: "SalesSourceTouches", type: "nvarchar(64)", maxLength: 64, nullable: false, oldClrType: typeof(string), oldType: "nvarchar(1000)", oldMaxLength: 1000);
        m.CreateIndex("IX_SalesAcquisitionCampaigns_CompanyId_Name","SalesAcquisitionCampaigns",new[]{"CompanyId","Name"}); m.CreateIndex("IX_SalesAcquisitionCampaigns_CompanyId_Provider_ExternalReference","SalesAcquisitionCampaigns",new[]{"CompanyId","Provider","ExternalReference"}); m.CreateIndex("IX_SalesContactPermissions_CompanyId_ContactId_Channel_Address","SalesContactPermissions",new[]{"CompanyId","ContactId","Channel","Address"},unique:true); m.CreateIndex("IX_SalesSourceAttributions_CompanyId_SubjectType_SubjectId","SalesSourceAttributions",new[]{"CompanyId","SubjectType","SubjectId"},unique:true); m.CreateIndex("IX_SalesSourceTouches_CampaignId","SalesSourceTouches","CampaignId"); m.CreateIndex("IX_SalesSourceTouches_CompanyId_DedupeKey","SalesSourceTouches",new[]{"CompanyId","DedupeKey"},unique:true); m.CreateIndex("IX_SalesSourceTouches_CompanyId_SubjectType_SubjectId_ObservedUtc","SalesSourceTouches",new[]{"CompanyId","SubjectType","SubjectId","ObservedUtc"});
        m.Sql("""
UPDATE agent_templates SET tool_permissions_json = N'{"allowed":["sales.plan_prospecting_run","sales.start_prospecting_run","sales.list_prospects","sales.research_prospect","sales.recommend_prospect_decision"],"actions":["read","recommend","execute"],"denied":[],"deniedActions":[]}', data_scopes_json = N'{"read":["sales","prospecting"],"recommend":["sales","prospecting"],"execute":["sales","prospecting"],"write":[]}' WHERE [TemplateId] = N'sales';
UPDATE agents SET tool_permissions_json = N'{"allowed":["sales.plan_prospecting_run","sales.start_prospecting_run","sales.list_prospects","sales.research_prospect","sales.recommend_prospect_decision"],"actions":["read","recommend","execute"],"denied":[],"deniedActions":[]}', data_scopes_json = N'{"read":["sales","prospecting"],"recommend":["sales","prospecting"],"execute":["sales","prospecting"],"write":[]}' WHERE [TemplateId] = N'sales';
""");
    }
    protected override void Down(MigrationBuilder m) { m.Sql("UPDATE agent_templates SET tool_permissions_json = N'{\"allowed\":[\"crm\",\"email\",\"calendar\",\"proposal\"]}', data_scopes_json = N'{\"read\":[\"accounts\",\"contacts\",\"opportunities\"],\"write\":[\"opportunity_notes\",\"followup_tasks\",\"pipeline_updates\"]}' WHERE [TemplateId] = N'sales'; UPDATE agents SET tool_permissions_json = N'{\"allowed\":[\"crm\",\"email\",\"calendar\",\"proposal\"]}', data_scopes_json = N'{\"read\":[\"accounts\",\"contacts\",\"opportunities\"],\"write\":[\"opportunity_notes\",\"followup_tasks\",\"pipeline_updates\"]}' WHERE [TemplateId] = N'sales';"); m.DropTable("SalesContactPermissions"); m.DropTable("SalesSourceAttributions"); m.DropTable("SalesSourceTouches"); m.DropTable("SalesAcquisitionCampaigns"); }
}
