// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VirtualCompany.Infrastructure.Persistence;

#nullable disable

namespace VirtualCompany.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VirtualCompanyDbContext))]
    partial class VirtualCompanyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VirtualCompany.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DataSources")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("data_sources_json")
                        .HasDefaultValueSql("N'[]'");

                    b.Property<string>("DataSourcesUsed")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("data_sources_used_json")
                        .HasDefaultValueSql("N'[]'");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata_json")
                        .HasDefaultValueSql("N'{}'");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("RelatedAgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedApprovalRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedToolExecutionAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedWorkflowInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RationaleSummary")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "ActorType", "ActorId");

                    b.HasIndex("CompanyId", "CorrelationId");

                    b.HasIndex("CompanyId", "OccurredUtc");

                    b.HasIndex("CompanyId", "RelatedAgentId", "OccurredUtc");

                    b.HasIndex("CompanyId", "RelatedApprovalRequestId", "OccurredUtc");

                    b.HasIndex("CompanyId", "RelatedTaskId", "OccurredUtc");

                    b.HasIndex("CompanyId", "RelatedToolExecutionAttemptId", "OccurredUtc");

                    b.HasIndex("CompanyId", "RelatedWorkflowInstanceId", "OccurredUtc");

                    b.HasIndex("CompanyId", "TargetType", "TargetId", "OccurredUtc");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("VirtualCompany.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EscalationRules")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("escalation_rules_json")
                        .HasDefaultValueSql("N'{}'");

                    b.Property<string>("Kpis")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kpis_json")
                        .HasDefaultValueSql("N'{}'");

                    b.Property<string>("Objectives")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("objectives_json")
                        .HasDefaultValueSql("N'{}'");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("personality_json")
                        .HasDefaultValueSql("N'{}'");

                    b.Property<string>("RoleBrief")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("role_brief");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("data_scopes_json")
                        .HasDefaultValueSql("N'{}'");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("active");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Thresholds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("approval_thresholds_json")
                        .HasDefaultValueSql("N'{}'");

                    b.Property<string>("TriggerLogic")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trigger_logic_json")
                        .HasDefaultValueSql("N'{}'");

                    b.Property<string>("Tools")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tool_permissions_json")
                        .HasDefaultValueSql("N'{}'");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkingHours")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("working_hours_json")
                        .HasDefaultValueSql("N'{}'");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Department");

                    b.HasIndex("CompanyId", "Department", "Status");

                    b.HasIndex("CompanyId", "DisplayName");

                    b.HasIndex("CompanyId", "Status");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("VirtualCompany.Domain.Entities.AgentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultSeniority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EscalationRules")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("escalation_rules_json")
                        .HasDefaultValueSql("N'{}'");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Kpis")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kpis_json")
                        .HasDefaultValueSql("N'{}'");

                    b.Property<string>("Objectives")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("objectives_json")
                        .HasDefaultValueSql("N'{}'");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("personality_json")
                        .HasDefaultValueSql("N'{}'");

                    b.Property<string>("PersonaSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("data_scopes_json")
                        .HasDefaultValueSql("N'{}'");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Thresholds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("approval_thresholds_json")
                        .HasDefaultValueSql("N'{}'");

                    b.Property<string>("Tools")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tool_permissions_json")
                        .HasDefaultValueSql("N'{}'");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "SortOrder");

                    b.HasIndex("TemplateId")
                        .IsUnique();

                    b.HasData(
                        new
                        {
                            Id = new Guid("3cda0f7c-0cb5-4b4f-9cf2-1a5b25f30101"),
                            AvatarUrl = "/avatars/agents/finance-manager.png",
                            CreatedUtc = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeniority = "senior",
                            Department = "Finance",
                            EscalationRules = "{\"critical\":[\"cash_runway_under_90_days\",\"failed_payroll_run\"],\"escalateTo\":\"founder\"}",
                            IsActive = true,
                            Kpis = "{\"targets\":[\"monthly_close_under_5_days\",\"forecast_variance_under_3_percent\",\"late_invoices_under_2_percent\"]}",
                            Objectives = "{\"primary\":[\"Protect cash flow\",\"Maintain accurate books\",\"Reduce avoidable spend leakage\"]}",
                            Personality = "{\"summary\":\"Calm, precise, audit-ready communicator.\",\"traits\":[\"detail-oriented\",\"risk-aware\",\"structured\"]}",
                            PersonaSummary = "Cash-focused operator who keeps books clean, tracks runway, and escalates financial anomalies early.",
                            RoleName = "Finance Manager",
                            Scopes = "{\"read\":[\"finance\",\"payments\",\"vendors\"],\"write\":[\"forecast_drafts\",\"invoice_followups\"]}",
                            SortOrder = 10,
                            TemplateId = "finance",
                            Thresholds = "{\"approval\":{\"expenseUsd\":5000,\"wireTransferUsd\":2500}}",
                            Tools = "{\"allowed\":[\"erp\",\"accounting\",\"spreadsheets\",\"billing\"]}",
                            UpdatedUtc = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3cda0f7c-0cb5-4b4f-9cf2-1a5b25f30102"),
                            AvatarUrl = "/avatars/agents/sales-manager.png",
                            CreatedUtc = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeniority = "senior",
                            Department = "Sales",
                            EscalationRules = "{\"critical\":[\"deal_risk_over_50000\",\"forecast_slip_over_20_percent\"],\"escalateTo\":\"founder\"}",
                            IsActive = true,
                            Kpis = "{\"targets\":[\"weekly_sqls\",\"stage_conversion_rate\",\"forecast_accuracy\"]}",
                            Objectives = "{\"primary\":[\"Increase qualified pipeline\",\"Improve conversion velocity\",\"Protect forecast quality\"]}",
                            Personality = "{\"summary\":\"Direct, energetic, commercially sharp.\",\"traits\":[\"persistent\",\"concise\",\"target-driven\"]}",
                            PersonaSummary = "Pipeline builder who keeps follow-up tight, qualification clear, and forecast discipline visible.",
                            RoleName = "Sales Manager",
                            Scopes = "{\"read\":[\"accounts\",\"contacts\",\"opportunities\"],\"write\":[\"opportunity_notes\",\"followup_tasks\",\"pipeline_updates\"]}",
                            SortOrder = 20,
                            TemplateId = "sales",
                            Thresholds = "{\"discount\":{\"maxPercent\":10}}",
                            Tools = "{\"allowed\":[\"crm\",\"email\",\"calendar\",\"proposal\"]}",
                            UpdatedUtc = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3cda0f7c-0cb5-4b4f-9cf2-1a5b25f30103"),
                            AvatarUrl = "/avatars/agents/marketing-manager.png",
                            CreatedUtc = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeniority = "senior",
                            Department = "Marketing",
                            EscalationRules = "{\"critical\":[\"cac_spike_over_25_percent\",\"brand_incident\"],\"escalateTo\":\"founder\"}",
                            IsActive = true,
                            Kpis = "{\"targets\":[\"mql_volume\",\"cost_per_qualified_lead\",\"content_publish_cadence\"]}",
                            Objectives = "{\"primary\":[\"Grow qualified demand\",\"Improve campaign efficiency\",\"Increase content output consistency\"]}",
                            Personality = "{\"summary\":\"Creative, analytical, and outcome-focused.\",\"traits\":[\"experimental\",\"brand-aware\",\"data-literate\"]}",
                            PersonaSummary = "Demand-generation lead who connects campaigns, content, and attribution to revenue outcomes.",
                            RoleName = "Marketing Manager",
                            Scopes = "{\"read\":[\"campaigns\",\"analytics\",\"content_calendar\"],\"write\":[\"campaign_briefs\",\"draft_copy\",\"weekly_reports\"]}",
                            SortOrder = 30,
                            TemplateId = "marketing",
                            Thresholds = "{\"budget\":{\"monthlyPaidSpendUsd\":15000}}",
                            Tools = "{\"allowed\":[\"analytics\",\"cms\",\"email_marketing\",\"ads_manager\"]}",
                            UpdatedUtc = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3cda0f7c-0cb5-4b4f-9cf2-1a5b25f30104"),
                            AvatarUrl = "/avatars/agents/support-lead.png",
                            CreatedUtc = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeniority = "lead",
                            Department = "Support",
                            EscalationRules = "{\"critical\":[\"sev1_incident\",\"vip_customer_blocked\",\"csat_below_80\"],\"escalateTo\":\"operations\"}",
                            IsActive = true,
                            Kpis = "{\"targets\":[\"first_response_time\",\"resolution_time\",\"csat\",\"reopen_rate\"]}",
                            Objectives = "{\"primary\":[\"Protect first-response SLA\",\"Raise resolution quality\",\"Reduce repeat-contact drivers\"]}",
                            Personality = "{\"summary\":\"Empathetic, calm under pressure, and operationally disciplined.\",\"traits\":[\"patient\",\"service-oriented\",\"clear\"]}",
                            PersonaSummary = "Customer advocate who protects SLA health, improves resolution quality, and flags systemic issues fast.",
                            RoleName = "Support Lead",
                            Scopes = "{\"read\":[\"tickets\",\"customer_history\",\"knowledge_base\"],\"write\":[\"ticket_replies\",\"macro_updates\",\"triage_tags\"]}",
                            SortOrder = 40,
                            TemplateId = "support",
                            Thresholds = "{\"sla\":{\"firstResponseMinutes\":30,\"resolutionHours\":24}}",
                            Tools = "{\"allowed\":[\"ticketing\",\"knowledge_base\",\"chat\",\"incident_tracking\"]}",
                            UpdatedUtc = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3cda0f7c-0cb5-4b4f-9cf2-1a5b25f30105"),
                            AvatarUrl = "/avatars/agents/operations-manager.png",
                            CreatedUtc = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeniority = "lead",
                            Department = "Operations",
                            EscalationRules = "{\"critical\":[\"missed_customer_deadline\",\"systemic_handoff_failure\"],\"escalateTo\":\"founder\"}",
                            IsActive = true,
                            Kpis = "{\"targets\":[\"sla_adherence\",\"handoff_error_rate\",\"cycle_time\",\"backlog_age\"]}",
                            Objectives = "{\"primary\":[\"Reduce operational friction\",\"Improve handoff quality\",\"Surface delivery blockers early\"]}",
                            Personality = "{\"summary\":\"Systematic, decisive, and accountability-heavy.\",\"traits\":[\"process-minded\",\"reliable\",\"cross-functional\"]}",
                            PersonaSummary = "Execution owner who keeps workflows stable, handoffs clear, and delivery risks visible across the company.",
                            RoleName = "Operations Manager",
                            Scopes = "{\"read\":[\"workflows\",\"projects\",\"operational_metrics\"],\"write\":[\"runbooks\",\"task_assignments\",\"retrospective_notes\"]}",
                            SortOrder = 50,
                            TemplateId = "operations",
                            Thresholds = "{\"delivery\":{\"blockedDays\":2}}",
                            Tools = "{\"allowed\":[\"project_management\",\"docs\",\"incident_tracking\",\"calendar\"]}",
                            UpdatedUtc = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3cda0f7c-0cb5-4b4f-9cf2-1a5b25f30106"),
                            AvatarUrl = "/avatars/agents/executive-assistant.png",
                            CreatedUtc = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeniority = "executive",
                            Department = "Executive",
                            EscalationRules = "{\"critical\":[\"board_meeting_change\",\"executive_deadline_at_risk\"],\"escalateTo\":\"founder\"}",
                            IsActive = true,
                            Kpis = "{\"targets\":[\"calendar_conflict_rate\",\"followup_completion_rate\",\"meeting_preparation_coverage\"]}",
                            Objectives = "{\"primary\":[\"Protect executive focus time\",\"Track commitments to completion\",\"Improve meeting quality\"]}",
                            Personality = "{\"summary\":\"Polished, anticipatory, and extremely organized.\",\"traits\":[\"discreet\",\"proactive\",\"detail-oriented\"]}",
                            PersonaSummary = "Founder support partner who organizes follow-through, protects calendar focus, and keeps leadership commitments moving.",
                            RoleName = "Executive Assistant",
                            Scopes = "{\"read\":[\"calendar\",\"meeting_notes\",\"priority_projects\"],\"write\":[\"agenda_drafts\",\"followup_lists\",\"calendar_holds\"]}",
                            SortOrder = 60,
                            TemplateId = "executive-assistant",
                            Thresholds = "{\"calendar\":{\"maxBackToBackMeetings\":4}}",
                            Tools = "{\"allowed\":[\"calendar\",\"email\",\"docs\",\"task_management\"]}",
                            UpdatedUtc = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc)
                        });

                    b.ToTable("agent_templates", (string)null);
                });

            modelBuilder.Entity("VirtualCompany.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Branding")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("branding_json")
                        .HasDefaultValueSql("N'{}'");

                    b.Property<string>("BusinessType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ComplianceRegion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("OnboardingAbandonedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OnboardingCompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OnboardingCurrentStep")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OnboardingLastSavedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OnboardingStateJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnboardingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("not_started");

                    b.Property<string>("OnboardingTemplateId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("settings_json")
                        .HasDefaultValueSql("N'{}'");

                    b.Property<string>("Timezone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OnboardingCompletedUtc");

                    b.HasIndex("OnboardingStatus");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("VirtualCompany.Domain.Entities.CompanyInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveredUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("pending");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastDeliveredTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("LastDeliveryAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastDeliveryCorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("LastSentUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedByUserId");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("CompanyId", "DeliveryStatus");

                    b.HasIndex("CompanyId", "Email")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'pending'");

                    b.HasIndex("CompanyId", "Status", "ExpiresAtUtc");

                    b.ToTable("company_invitations", (string)null);
                });

            modelBuilder.Entity("VirtualCompany.Domain.Entities.CompanyMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvitedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MembershipAccessConfigurationJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("permissions_json");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "InvitedEmail")
                        .IsUnique()
                        .HasFilter("\"InvitedEmail\" IS NOT NULL");

                    b.HasIndex("CompanyId", "UserId")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.HasIndex("UserId", "Status")
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("company_memberships", (string)null);
                });

            modelBuilder.Entity("VirtualCompany.Domain.Entities.CompanyOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("AvailableUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClaimToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("ClaimedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CausationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HeadersJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("MessageType")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("pending");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "CreatedUtc");

                    b.HasIndex("CompanyId", "Topic", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.HasIndex("CompanyId", "Status", "AvailableUtc");

                    b.HasIndex("CompanyId", "ProcessedUtc");

                    b.HasIndex("ProcessedUtc", "ClaimedUtc");
                    b.HasIndex("ProcessedUtc", "AvailableUtc", "AttemptCount");

                    b.HasIndex("Status", "AvailableUtc");

                    b.ToTable("company_outbox_messages", (string)null);
                });

            modelBuilder.Entity("VirtualCompany.Domain.Entities.CompanyOwnedNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Id");

                    b.ToTable("company_notes", (string)null);
                });

            modelBuilder.Entity("VirtualCompany.Domain.Entities.CompanySetupTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessTypeTag")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Defaults")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("defaults_json")
                        .HasDefaultValueSql("N'{}'");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("IndustryTag")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata_json")
                        .HasDefaultValueSql("N'{}'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId")
                        .IsUnique();

                    b.ToTable("company_setup_templates", (string)null);
                });

            modelBuilder.Entity("VirtualCompany.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AuthSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("AuthProvider", "AuthSubject")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("VirtualCompany.Domain.Entities.AuditEvent", b =>
                {
                    b.HasOne("VirtualCompany.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("VirtualCompany.Domain.Entities.Agent", b =>
                {
                    b.HasOne("VirtualCompany.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("VirtualCompany.Domain.Entities.CompanyInvitation", b =>
                {
                    b.HasOne("VirtualCompany.Domain.Entities.User", "AcceptedByUser")
                        .WithMany()
                        .HasForeignKey("AcceptedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VirtualCompany.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualCompany.Domain.Entities.User", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcceptedByUser");

                    b.Navigation("Company");

                    b.Navigation("InvitedByUser");
                });

            modelBuilder.Entity("VirtualCompany.Domain.Entities.CompanyMembership", b =>
                {
                    b.HasOne("VirtualCompany.Domain.Entities.Company", "Company")
                        .WithMany("Memberships")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualCompany.Domain.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VirtualCompany.Domain.Entities.CompanyOutboxMessage", b =>
                {
                    b.HasOne("VirtualCompany.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("VirtualCompany.Domain.Entities.CompanyOwnedNote", b =>
                {
                    b.HasOne("VirtualCompany.Domain.Entities.Company", "Company")
                        .WithMany("Notes")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("VirtualCompany.Domain.Entities.Company", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("VirtualCompany.Domain.Entities.User", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
