using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using VirtualCompany.Application.Marketing;
using VirtualCompany.Domain.Entities;
using VirtualCompany.Infrastructure.Persistence;

namespace VirtualCompany.Infrastructure.Sales;

public sealed class MarketingMeasurementService(VirtualCompanyDbContext db):IMarketingMeasurementService
{
    public async Task<MarketingAttributionTouchDto> RecordTouchAsync(Guid companyId,RecordMarketingAttributionTouchRequest r,CancellationToken ct){var e=await db.MarketingAttributionTouches.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.IdempotencyKey==r.IdempotencyKey,ct);if(e is null){e=new(Guid.NewGuid(),companyId,r.SubjectType,r.SubjectId,r.TouchType,r.Channel,r.SourceReference,r.SourceVersion,r.OccurredUtc,r.Cost,r.Currency,r.EvidenceJson,r.IdempotencyKey);db.Add(e);await db.SaveChangesAsync(ct);}return new(e.Id,e.SubjectType,e.SubjectId,e.TouchType,e.Channel,e.SourceReference,e.SourceVersion,e.OccurredUtc,e.Cost,e.Currency,e.EvidenceJson);}
    public async Task<MarketingAttributionModelDto> CreateModelAsync(Guid companyId,CreateMarketingAttributionModelRequest r,CancellationToken ct){var e=await db.MarketingAttributionModels.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.IdempotencyKey==r.IdempotencyKey,ct);if(e is null){var v=(await db.MarketingAttributionModels.IgnoreQueryFilters().Where(x=>x.CompanyId==companyId&&x.Name==r.Name).MaxAsync(x=>(int?)x.Version,ct)??0)+1;e=new(Guid.NewGuid(),companyId,r.Name,r.ModelType,v,r.RulesJson,r.Limitations,r.LookbackDays,r.IdempotencyKey);db.Add(e);await db.SaveChangesAsync(ct);}return new(e.Id,e.Name,e.ModelType,e.Version,e.RulesJson,e.Limitations,e.LookbackDays);}
    public async Task<MarketingAttributionRunDto> RunAttributionAsync(Guid companyId,RunMarketingAttributionRequest r,CancellationToken ct){var prior=await db.MarketingAttributionResults.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.IdempotencyKey==r.IdempotencyKey,ct);if(prior is not null){var pa=await db.MarketingAttributionAllocations.IgnoreQueryFilters().Where(x=>x.CompanyId==companyId&&x.MarketingAttributionResultId==prior.Id).ToListAsync(ct);return MapRun(prior,pa,"Previously computed from immutable input versions.");}var model=await db.MarketingAttributionModels.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.Id==r.ModelId,ct)??throw new InvalidOperationException("Attribution model is unavailable.");var touches=await db.MarketingAttributionTouches.IgnoreQueryFilters().AsNoTracking().Where(x=>x.CompanyId==companyId&&x.SubjectType==r.SubjectType&&x.SubjectId==r.SubjectId&&x.OccurredUtc>=r.PeriodStartUtc&&x.OccurredUtc<=r.PeriodEndUtc).OrderBy(x=>x.OccurredUtc).ToListAsync(ct);if(touches.Count==0)throw new InvalidOperationException("No immutable attribution touches are available.");var weights=Weights(model,touches);var evidenceVersion=$"model:{model.Id:N}:v{model.Version}:touches:{string.Join('-',touches.Select(x=>x.SourceVersion))}";var result=new MarketingAttributionResult(Guid.NewGuid(),companyId,r.SubjectType,r.SubjectId,$"{model.ModelType}:v{model.Version}","configured_rule",r.OutcomeValue,r.Unit,JsonSerializer.Serialize(new{model.Id,model.Version,touchIds=touches.Select(x=>x.Id),model.Limitations,evidenceVersion}),.75m,r.PeriodStartUtc,r.PeriodEndUtc,r.IdempotencyKey);db.Add(result);var allocations=touches.Select((x,i)=>new MarketingAttributionAllocation(Guid.NewGuid(),companyId,result.Id,x.Id,weights[i],decimal.Round(r.OutcomeValue*weights[i],4),evidenceVersion)).ToArray();db.AddRange(allocations);await db.SaveChangesAsync(ct);return MapRun(result,allocations,model.Limitations);}
    public async Task RecordExposureAsync(Guid companyId,RecordMarketingExperimentExposureRequest r,CancellationToken ct){if(await db.MarketingExperimentExposures.IgnoreQueryFilters().AnyAsync(x=>x.CompanyId==companyId&&x.MarketingExperimentId==r.ExperimentId&&x.AssignmentKey==r.AssignmentKey,ct))return;if(!await db.MarketingExperiments.IgnoreQueryFilters().AnyAsync(x=>x.CompanyId==companyId&&x.Id==r.ExperimentId,ct))throw new InvalidOperationException("Experiment is unavailable.");db.Add(new MarketingExperimentExposure(Guid.NewGuid(),companyId,r.ExperimentId,r.SubjectReference,r.Variant,r.AssignmentKey,r.ExposedUtc,r.EvidenceJson));await db.SaveChangesAsync(ct);}
    public async Task<MarketingExperimentDecisionDto> EvaluateExperimentAsync(Guid companyId,EvaluateMarketingExperimentRequest r,CancellationToken ct){var old=await db.MarketingExperimentDecisions.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.MarketingExperimentId==r.ExperimentId,ct);if(old is not null)return Map(old);if(!await db.MarketingExperiments.IgnoreQueryFilters().AnyAsync(x=>x.CompanyId==companyId&&x.Id==r.ExperimentId,ct))throw new InvalidOperationException("Experiment is unavailable.");var p=MarketingExperimentDecisionPolicy.Evaluate(r.MinimumSampleSize,r.SampleSize,r.ContaminationRate,r.DataQualityValid,r.GuardrailBreached);var e=new MarketingExperimentDecisionRecord(Guid.NewGuid(),companyId,r.ExperimentId,p.Decision,r.SampleSize,r.ContaminationRate,r.GuardrailBreached,p.CausalEligible,r.EvidenceJson,p.Limitation);db.Add(e);await db.SaveChangesAsync(ct);return Map(e);}
    public async Task<MarketingSegmentLearningProposalDto> ProposeSegmentLearningAsync(Guid companyId,CreateMarketingSegmentLearningProposalRequest r,CancellationToken ct){var e=await db.MarketingSegmentLearningProposals.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.IdempotencyKey==r.IdempotencyKey,ct);if(e is null){if(!await db.MarketingCustomerSegmentVersions.IgnoreQueryFilters().AnyAsync(x=>x.CompanyId==companyId&&x.Id==r.SegmentVersionId,ct))throw new InvalidOperationException("Segment version is unavailable.");e=new(Guid.NewGuid(),companyId,r.SegmentVersionId,r.MetricsJson,r.ProposedChangesJson,r.EvidenceJson,r.Confidence,r.IdempotencyKey);db.Add(e);await db.SaveChangesAsync(ct);}return new(e.Id,e.MarketingCustomerSegmentVersionId,e.MetricsJson,e.ProposedChangesJson,e.EvidenceJson,e.Confidence,e.Status,e.CreatedUtc);}
    private static decimal[] Weights(MarketingAttributionModelDefinition m,IReadOnlyList<MarketingAttributionTouch> t){var w=new decimal[t.Count];if(m.ModelType=="first_touch")w[0]=1;else if(m.ModelType=="last_touch")w[^1]=1;else if(m.ModelType=="configured_weighted"){using var d=JsonDocument.Parse(m.RulesJson);var a=d.RootElement.GetProperty("weights").EnumerateArray().Select(x=>x.GetDecimal()).ToArray();if(a.Length!=t.Count||a.Sum()!=1)throw new InvalidOperationException("Configured weights must match touches and total one.");w=a;}else for(var i=0;i<w.Length;i++)w[i]=1m/w.Length;return w;}
    private static MarketingAttributionRunDto MapRun(MarketingAttributionResult r,IReadOnlyList<MarketingAttributionAllocation>a,string l)=>new(new(r.Id,r.SubjectType,r.SubjectId,r.Model,r.Classification,r.AttributedValue,r.Unit,r.EvidenceJson,r.Confidence,r.PeriodStartUtc,r.PeriodEndUtc,r.CreatedUtc),a.Select(x=>new MarketingAttributionAllocationDto(x.MarketingAttributionTouchId,x.Weight,x.AttributedValue,x.EvidenceVersion)).ToArray(),l);
    private static MarketingExperimentDecisionDto Map(MarketingExperimentDecisionRecord x)=>new(x.Id,x.MarketingExperimentId,x.Decision,x.SampleSize,x.ContaminationRate,x.GuardrailBreached,x.CausalEligible,x.EvidenceJson,x.Limitations);
}
