<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VirtualCompany.Infrastructure.Platform\VirtualCompany.Infrastructure.Platform.csproj" />
    <ProjectReference Include="..\VirtualCompany.Infrastructure.Mailbox\VirtualCompany.Infrastructure.Mailbox.csproj" />
    <ProjectReference Include="..\VirtualCompany.Infrastructure.Finance\VirtualCompany.Infrastructure.Finance.csproj" />
    <ProjectReference Include="..\VirtualCompany.Infrastructure.Sales\VirtualCompany.Infrastructure.Sales.csproj" />
    <ProjectReference Include="..\VirtualCompany.Infrastructure.Support\VirtualCompany.Infrastructure.Support.csproj" />
    <ProjectReference Include="..\VirtualCompany.Infrastructure.Operations\VirtualCompany.Infrastructure.Operations.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
