using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using VirtualCompany.Domain.Entities;
namespace VirtualCompany.Infrastructure.Persistence;
internal sealed class AnnualPlanConfiguration:IEntityTypeConfiguration<AnnualPlanVersion>
{
 public void Configure(EntityTypeBuilder<AnnualPlanVersion>b){b.ToTable("annual_plan_versions");b.HasKey(x=>x.Id);b.HasAlternateKey(x=>new{x.CompanyId,x.Id});b.HasIndex(x=>new{x.CompanyId,x.FiscalYear,x.Version}).IsUnique();b.HasIndex(x=>new{x.CompanyId,x.RequestId}).IsUnique();b.HasIndex(x=>new{x.CompanyId,x.PreviousId}).IsUnique().HasFilter("[PreviousId] IS NOT NULL");b.Property(x=>x.StateRevision).IsConcurrencyToken();b.Property(x=>x.Status).HasMaxLength(32);b.Property(x=>x.Notes).HasMaxLength(4000);b.Property(x=>x.Fingerprint).HasMaxLength(64);b.Property(x=>x.CommandHash).HasMaxLength(64);b.Property(x=>x.Currency).HasMaxLength(3);b.Property(x=>x.Timezone).HasMaxLength(128);b.Property(x=>x.StartUtc).HasConversion(v=>v,v=>DateTime.SpecifyKind(v,DateTimeKind.Utc));b.Property(x=>x.EndUtc).HasConversion(v=>v,v=>DateTime.SpecifyKind(v,DateTimeKind.Utc));b.Property(x=>x.SavedUtc).HasConversion(v=>v,v=>DateTime.SpecifyKind(v,DateTimeKind.Utc));b.HasOne<ApprovalRequest>().WithMany().HasForeignKey(x=>new{x.CompanyId,Id=x.ApprovalId}).HasPrincipalKey(x=>new{x.CompanyId,x.Id}).OnDelete(DeleteBehavior.NoAction);b.HasOne<Company>().WithMany().HasForeignKey(x=>x.CompanyId).OnDelete(DeleteBehavior.Cascade);b.HasOne<AnnualPlanVersion>().WithMany().HasForeignKey(x=>new{x.CompanyId,Id=x.PreviousId}).HasPrincipalKey(x=>new{x.CompanyId,x.Id}).OnDelete(DeleteBehavior.NoAction);b.HasMany(x=>x.Objectives).WithOne().HasForeignKey(x=>new{x.CompanyId,x.PlanId}).HasPrincipalKey(x=>new{x.CompanyId,x.Id});b.HasMany(x=>x.Budgets).WithOne().HasForeignKey(x=>new{x.CompanyId,x.PlanId}).HasPrincipalKey(x=>new{x.CompanyId,x.Id});b.HasMany(x=>x.Allocations).WithOne().HasForeignKey(x=>new{x.CompanyId,x.PlanId}).HasPrincipalKey(x=>new{x.CompanyId,x.Id});}
}
internal sealed class AnnualObjectiveConfiguration:IEntityTypeConfiguration<AnnualObjective>{public void Configure(EntityTypeBuilder<AnnualObjective>b){b.ToTable("annual_objectives");b.HasKey(x=>x.Id);b.HasAlternateKey(x=>new{x.CompanyId,x.Id});b.HasIndex(x=>new{x.PlanId,x.GoalId}).IsUnique();b.Property(x=>x.Name).HasMaxLength(200);b.Property(x=>x.OwnerName).HasMaxLength(200);b.Property(x=>x.Unit).HasMaxLength(64);b.Property(x=>x.MetricKey).HasMaxLength(128);b.Property(x=>x.SourceFingerprint).HasMaxLength(64);b.Property(x=>x.Baseline).HasPrecision(19,4);b.Property(x=>x.Target).HasPrecision(19,4);b.HasOne<CompanyGoal>().WithMany().HasForeignKey(x=>new{x.CompanyId,x.GoalId}).HasPrincipalKey(x=>new{x.CompanyId,x.Id}).OnDelete(DeleteBehavior.NoAction);b.HasOne<QuarterlyReview>().WithMany().HasForeignKey(x=>new{x.CompanyId,Id=x.BaselineReviewId}).HasPrincipalKey(x=>new{x.CompanyId,x.Id}).OnDelete(DeleteBehavior.NoAction);b.HasMany(x=>x.Milestones).WithOne().HasForeignKey(x=>new{x.CompanyId,x.ObjectiveId}).HasPrincipalKey(x=>new{x.CompanyId,x.Id});b.HasMany(x=>x.Dependencies).WithOne().HasForeignKey(x=>new{x.CompanyId,x.ObjectiveId}).HasPrincipalKey(x=>new{x.CompanyId,x.Id});}}
internal sealed class AnnualMilestoneConfiguration:IEntityTypeConfiguration<AnnualMilestone>{public void Configure(EntityTypeBuilder<AnnualMilestone>b){b.ToTable("annual_milestones");b.HasKey(x=>x.Id);b.Property(x=>x.Title).HasMaxLength(200);b.Property(x=>x.DueUtc).HasConversion(v=>v,v=>DateTime.SpecifyKind(v,DateTimeKind.Utc));b.HasIndex(x=>new{x.ObjectiveId,x.Quarter}).IsUnique();}}
internal sealed class AnnualDependencyConfiguration:IEntityTypeConfiguration<AnnualDependency>{public void Configure(EntityTypeBuilder<AnnualDependency>b){b.ToTable("annual_dependencies");b.HasKey(x=>x.Id);b.Property(x=>x.Description).HasMaxLength(2000);b.HasIndex(x=>new{x.ObjectiveId,x.InitiativeId}).IsUnique();b.HasOne<OperatingInitiative>().WithMany().HasForeignKey(x=>new{x.CompanyId,Id=x.InitiativeId}).HasPrincipalKey(x=>new{x.CompanyId,x.Id}).OnDelete(DeleteBehavior.NoAction);}}
internal sealed class AnnualBudgetBindingConfiguration:IEntityTypeConfiguration<AnnualBudgetBinding>{public void Configure(EntityTypeBuilder<AnnualBudgetBinding>b){b.ToTable("annual_budget_bindings");b.HasKey(x=>x.Id);b.HasIndex(x=>new{x.PlanId,x.BudgetId}).IsUnique();b.Property(x=>x.Account).HasMaxLength(200);b.Property(x=>x.NativeVersion).HasMaxLength(64);b.Property(x=>x.Currency).HasMaxLength(3);b.Property(x=>x.SourceFingerprint).HasMaxLength(64);b.Property(x=>x.Amount).HasPrecision(19,2);b.HasOne<Budget>().WithMany().HasForeignKey(x=>new{x.CompanyId,Id=x.BudgetId}).HasPrincipalKey(x=>new{x.CompanyId,x.Id}).OnDelete(DeleteBehavior.NoAction);}}
internal sealed class AnnualAllocationConfiguration:IEntityTypeConfiguration<AnnualAllocation>{public void Configure(EntityTypeBuilder<AnnualAllocation>b){b.ToTable("annual_allocations");b.HasKey(x=>x.Id);b.Property(x=>x.Title).HasMaxLength(200);b.Property(x=>x.Kind).HasMaxLength(32);b.Property(x=>x.Amount).HasPrecision(19,2);b.HasOne<Budget>().WithMany().HasForeignKey(x=>new{x.CompanyId,Id=x.BudgetId}).HasPrincipalKey(x=>new{x.CompanyId,x.Id}).OnDelete(DeleteBehavior.NoAction);b.HasOne<CompanyGoal>().WithMany().HasForeignKey(x=>new{x.CompanyId,Id=x.GoalId}).HasPrincipalKey(x=>new{x.CompanyId,x.Id}).OnDelete(DeleteBehavior.NoAction);}}

