using System.Text.Json.Nodes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using VirtualCompany.Domain.Entities;
using VirtualCompany.Domain.Enums;

namespace VirtualCompany.Infrastructure.Persistence;

internal sealed class OperatingCycleConfiguration : IEntityTypeConfiguration<OperatingCycle>
{
    public void Configure(EntityTypeBuilder<OperatingCycle> b)
    {
        b.ToTable("operating_cycles"); b.HasKey(x => x.Id); Ids(b); b.Property(x => x.TriggerType).HasColumnName("trigger_type").HasMaxLength(64).IsRequired();
        b.Property(x => x.TriggerReference).HasColumnName("trigger_reference").HasMaxLength(256); b.Property(x => x.CoordinatorAgentId).HasColumnName("coordinator_agent_id").IsRequired();
        b.Property(x => x.Status).HasColumnName("status").HasConversion(x => x.ToStorageValue(), x => OperatingCycleStatusValues.Parse(x)).HasMaxLength(32).IsRequired();
        b.Property(x => x.ConfigurationVersion).HasColumnName("configuration_version"); b.Property(x => x.CorrelationId).HasColumnName("correlation_id").HasMaxLength(128).IsRequired();
        b.Property(x => x.IdempotencyKey).HasColumnName("idempotency_key").HasMaxLength(200).IsRequired(); b.Property(x => x.SnapshotId).HasColumnName("snapshot_id");
        b.Property(x => x.ModelCallsUsed).HasColumnName("model_calls_used"); b.Property(x => x.ToolCallsUsed).HasColumnName("tool_calls_used"); b.Property(x => x.TasksCreated).HasColumnName("tasks_created");
        b.Property(x => x.MonetaryBudgetUsed).HasColumnName("monetary_budget_used").HasPrecision(19, 4); b.Property(x => x.FailureCode).HasColumnName("failure_code").HasMaxLength(100); b.Property(x => x.FailureSummary).HasColumnName("failure_summary").HasMaxLength(2000);
        b.Property(x => x.RequestedUtc).HasColumnName("requested_at"); b.Property(x => x.StartedUtc).HasColumnName("started_at"); b.Property(x => x.CompletedUtc).HasColumnName("completed_at"); Times(b);
        b.HasIndex(x => new { x.CompanyId, x.IdempotencyKey }).IsUnique(); b.HasIndex(x => new { x.CompanyId, x.Status, x.RequestedUtc });
        b.HasOne(x => x.Company).WithMany().HasForeignKey(x => x.CompanyId).OnDelete(DeleteBehavior.Cascade); b.HasOne(x => x.CoordinatorAgent).WithMany().HasForeignKey(x => x.CoordinatorAgentId).OnDelete(DeleteBehavior.NoAction);
    }
    internal static void Ids<T>(EntityTypeBuilder<T> b) where T : class, ICompanyOwnedEntity { b.Property<Guid>("Id").HasColumnName("id"); b.Property(x => x.CompanyId).HasColumnName("company_id").IsRequired(); }
    internal static void Times<T>(EntityTypeBuilder<T> b) where T : class { b.Property<DateTime>("CreatedUtc").HasColumnName("created_at"); b.Property<DateTime>("UpdatedUtc").HasColumnName("updated_at"); }
}

internal sealed class OperatingPlanConfiguration : IEntityTypeConfiguration<OperatingPlan>
{
    public void Configure(EntityTypeBuilder<OperatingPlan> b) { b.ToTable("operating_plans"); b.HasKey(x => x.Id); OperatingCycleConfiguration.Ids(b); b.Property(x => x.CycleId).HasColumnName("cycle_id"); b.Property(x => x.SupersedesPlanId).HasColumnName("supersedes_plan_id"); b.Property(x => x.Version).HasColumnName("version"); b.Property(x => x.Status).HasColumnName("status").HasConversion(x => x.ToStorageValue(), x => OperatingPlanStatusValues.Parse(x)).HasMaxLength(32); b.Property(x => x.Objective).HasColumnName("objective").HasMaxLength(2000); b.Property(x => x.RationaleSummary).HasColumnName("rationale_summary").HasMaxLength(4000); b.Property(x => x.Uncertainty).HasColumnName("uncertainty_json").HasJsonConversion<Dictionary<string, JsonNode?>>().HasDefaultValueSql(CompanyJsonColumnConfiguration.JsonObjectDefault); OperatingCycleConfiguration.Times(b); b.Property(x => x.ReviewedUtc).HasColumnName("reviewed_at"); b.Property(x => x.CommittedUtc).HasColumnName("committed_at"); b.HasIndex(x => new { x.CompanyId, x.CycleId, x.Version }).IsUnique(); b.HasOne(x => x.Company).WithMany().HasForeignKey(x => x.CompanyId).OnDelete(DeleteBehavior.Cascade); b.HasOne(x => x.Cycle).WithMany(x => x.Plans).HasForeignKey(x => x.CycleId).OnDelete(DeleteBehavior.NoAction); b.HasOne(x => x.SupersedesPlan).WithMany().HasForeignKey(x => x.SupersedesPlanId).OnDelete(DeleteBehavior.NoAction); }
}

internal sealed class OperatingInitiativeConfiguration : IEntityTypeConfiguration<OperatingInitiative>
{
    public void Configure(EntityTypeBuilder<OperatingInitiative> b) { b.ToTable("operating_initiatives"); b.HasKey(x => x.Id); OperatingCycleConfiguration.Ids(b); b.Property(x => x.PlanId).HasColumnName("plan_id"); b.Property(x => x.GoalId).HasColumnName("goal_id"); b.Property(x => x.Title).HasColumnName("title").HasMaxLength(200); b.Property(x => x.DesiredOutcome).HasColumnName("desired_outcome").HasMaxLength(2000); b.Property(x => x.Priority).HasColumnName("priority").HasConversion(x => x.ToStorageValue(), x => CompanyGoalPriorityValues.Parse(x)).HasMaxLength(32); b.Property(x => x.Status).HasColumnName("status").HasConversion(x => x.ToStorageValue(), x => OperatingInitiativeStatusValues.Parse(x)).HasMaxLength(32); b.Property(x => x.CompletionEvidence).HasColumnName("completion_evidence").HasMaxLength(2000); b.Property(x => x.OwnerAgentId).HasColumnName("owner_agent_id"); b.Property(x => x.TargetUtc).HasColumnName("target_at"); b.Property(x => x.Budget).HasColumnName("budget").HasPrecision(19, 4); b.Property(x => x.TaskId).HasColumnName("task_id"); b.Property(x => x.WorkflowInstanceId).HasColumnName("workflow_instance_id"); b.Property(x => x.Version).HasColumnName("version").IsConcurrencyToken(); OperatingCycleConfiguration.Times(b); b.HasIndex(x => new { x.CompanyId, x.Status, x.TargetUtc }); b.HasOne(x => x.Plan).WithMany(x => x.Initiatives).HasForeignKey(x => x.PlanId).OnDelete(DeleteBehavior.Cascade); b.HasOne(x => x.Goal).WithMany().HasForeignKey(x => x.GoalId).OnDelete(DeleteBehavior.NoAction); b.HasOne(x => x.OwnerAgent).WithMany().HasForeignKey(x => x.OwnerAgentId).OnDelete(DeleteBehavior.NoAction); b.HasOne(x => x.Task).WithMany().HasForeignKey(x => x.TaskId).OnDelete(DeleteBehavior.NoAction); b.HasOne(x => x.WorkflowInstance).WithMany().HasForeignKey(x => x.WorkflowInstanceId).OnDelete(DeleteBehavior.NoAction); }
}

internal sealed class OperatingPlanDependencyConfiguration : IEntityTypeConfiguration<OperatingPlanDependency>
{
    public void Configure(EntityTypeBuilder<OperatingPlanDependency> b) { b.ToTable("operating_plan_dependencies"); b.HasKey(x => x.Id); OperatingCycleConfiguration.Ids(b); b.Property(x => x.PlanId).HasColumnName("plan_id"); b.Property(x => x.InitiativeId).HasColumnName("initiative_id"); b.Property(x => x.DependsOnInitiativeId).HasColumnName("depends_on_initiative_id"); b.HasIndex(x => new { x.CompanyId, x.PlanId, x.InitiativeId, x.DependsOnInitiativeId }).IsUnique(); b.HasOne(x => x.Plan).WithMany().HasForeignKey(x => x.PlanId).OnDelete(DeleteBehavior.Cascade); b.HasOne<OperatingInitiative>().WithMany().HasForeignKey(x => x.InitiativeId).OnDelete(DeleteBehavior.NoAction); b.HasOne<OperatingInitiative>().WithMany().HasForeignKey(x => x.DependsOnInitiativeId).OnDelete(DeleteBehavior.NoAction); }
}

internal sealed class OperatingDecisionConfiguration : IEntityTypeConfiguration<OperatingDecision>
{
    public void Configure(EntityTypeBuilder<OperatingDecision> b) { b.ToTable("operating_decisions"); b.HasKey(x => x.Id); OperatingCycleConfiguration.Ids(b); b.Property(x => x.PlanId).HasColumnName("plan_id"); b.Property(x => x.InitiativeId).HasColumnName("initiative_id"); b.Property(x => x.ActionClass).HasColumnName("action_class").HasConversion(x => x.ToStorageValue(), x => OperatingActionClassValues.Parse(x)).HasMaxLength(32); b.Property(x => x.ActionType).HasColumnName("action_type").HasMaxLength(128); b.Property(x => x.TargetType).HasColumnName("target_type").HasMaxLength(100); b.Property(x => x.TargetId).HasColumnName("target_id").HasMaxLength(200); b.Property(x => x.ProposedAgentId).HasColumnName("proposed_agent_id"); b.Property(x => x.RationaleSummary).HasColumnName("rationale_summary").HasMaxLength(2000); b.Property(x => x.Confidence).HasColumnName("confidence").HasPrecision(5, 4); b.Property(x => x.RiskLevel).HasColumnName("risk_level").HasMaxLength(32); b.Property(x => x.ApprovalRequired).HasColumnName("approval_required"); b.Property(x => x.IdempotencyKey).HasColumnName("idempotency_key").HasMaxLength(200); b.Property(x => x.CreatedUtc).HasColumnName("created_at"); b.HasIndex(x => new { x.CompanyId, x.IdempotencyKey }).IsUnique(); b.HasOne(x => x.Plan).WithMany(x => x.Decisions).HasForeignKey(x => x.PlanId).OnDelete(DeleteBehavior.Cascade); b.HasOne<OperatingInitiative>().WithMany().HasForeignKey(x => x.InitiativeId).OnDelete(DeleteBehavior.NoAction); b.HasOne<Agent>().WithMany().HasForeignKey(x => x.ProposedAgentId).OnDelete(DeleteBehavior.NoAction); }
}

internal sealed class OperatingValidationResultConfiguration : IEntityTypeConfiguration<OperatingValidationResult>
{
    public void Configure(EntityTypeBuilder<OperatingValidationResult> b) { b.ToTable("operating_validation_results"); b.HasKey(x => x.Id); OperatingCycleConfiguration.Ids(b); b.Property(x => x.PlanId).HasColumnName("plan_id"); b.Property(x => x.DecisionId).HasColumnName("decision_id"); b.Property(x => x.Validator).HasColumnName("validator").HasMaxLength(100); b.Property(x => x.ValidatorVersion).HasColumnName("validator_version").HasMaxLength(32); b.Property(x => x.Outcome).HasColumnName("outcome").HasConversion(x => x.ToStorageValue(), x => OperatingValidationOutcomeValues.Parse(x)).HasMaxLength(32); b.Property(x => x.ReasonCode).HasColumnName("reason_code").HasMaxLength(100); b.Property(x => x.Explanation).HasColumnName("explanation").HasMaxLength(2000); b.Property(x => x.ApprovalRequired).HasColumnName("approval_required"); b.Property(x => x.ConfigurationVersion).HasColumnName("configuration_version"); b.Property(x => x.Evidence).HasColumnName("evidence_json").HasJsonConversion<Dictionary<string, JsonNode?>>().HasDefaultValueSql(CompanyJsonColumnConfiguration.JsonObjectDefault); b.Property(x => x.EvaluatedUtc).HasColumnName("evaluated_at"); b.HasIndex(x => new { x.CompanyId, x.PlanId, x.Validator }); b.HasOne(x => x.Plan).WithMany(x => x.ValidationResults).HasForeignKey(x => x.PlanId).OnDelete(DeleteBehavior.Cascade); b.HasOne<OperatingDecision>().WithMany().HasForeignKey(x => x.DecisionId).OnDelete(DeleteBehavior.NoAction); }
}

internal sealed class OperatingReviewConfiguration : IEntityTypeConfiguration<OperatingReview>
{
    public void Configure(EntityTypeBuilder<OperatingReview> b) { b.ToTable("operating_reviews"); b.HasKey(x => x.Id); OperatingCycleConfiguration.Ids(b); b.Property(x => x.InitiativeId).HasColumnName("initiative_id"); b.Property(x => x.Outcome).HasColumnName("outcome").HasConversion(x => x.ToStorageValue(), x => OperatingReviewOutcomeValues.Parse(x)).HasMaxLength(32); b.Property(x => x.Summary).HasColumnName("summary").HasMaxLength(2000); b.Property(x => x.EvidenceVersion).HasColumnName("evidence_version").HasMaxLength(100); b.Property(x => x.Confidence).HasColumnName("confidence").HasPrecision(5, 4); b.Property(x => x.Evidence).HasColumnName("evidence_json").HasJsonConversion<Dictionary<string, JsonNode?>>().HasDefaultValueSql(CompanyJsonColumnConfiguration.JsonObjectDefault); b.Property(x => x.CreatedUtc).HasColumnName("created_at"); b.HasIndex(x => new { x.CompanyId, x.InitiativeId, x.EvidenceVersion }).IsUnique(); b.HasOne<OperatingInitiative>().WithMany().HasForeignKey(x => x.InitiativeId).OnDelete(DeleteBehavior.Cascade); }
}

internal sealed class OperatingSnapshotConfiguration : IEntityTypeConfiguration<OperatingSnapshot>
{
    public void Configure(EntityTypeBuilder<OperatingSnapshot> b) { b.ToTable("operating_snapshots"); b.HasKey(x => x.Id); OperatingCycleConfiguration.Ids(b); b.Property(x => x.CycleId).HasColumnName("cycle_id"); b.Property(x => x.SchemaVersion).HasColumnName("schema_version").HasMaxLength(32); b.Property(x => x.Payload).HasColumnName("payload_json").HasJsonConversion<Dictionary<string, JsonNode?>>().HasDefaultValueSql(CompanyJsonColumnConfiguration.JsonObjectDefault); b.Property(x => x.SourceCount).HasColumnName("source_count"); b.Property(x => x.DataGapCount).HasColumnName("data_gap_count"); b.Property(x => x.IsTruncated).HasColumnName("is_truncated"); b.Property(x => x.CreatedUtc).HasColumnName("created_at"); b.HasIndex(x => new { x.CompanyId, x.CycleId }).IsUnique(); b.HasOne<OperatingCycle>().WithMany().HasForeignKey(x => x.CycleId).OnDelete(DeleteBehavior.Cascade); }
}
