using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using VirtualCompany.Domain.Entities;

namespace VirtualCompany.Infrastructure.Persistence.Configurations;

internal static class MarketingMeasurementConfiguration
{ public static void I<T>(EntityTypeBuilder<T>b,string t)where T:class,ICompanyOwnedEntity{b.ToTable(t);b.HasKey("Id");b.Property<Guid>("Id").HasColumnName("id");b.Property(x=>x.CompanyId).HasColumnName("company_id");b.HasAlternateKey("CompanyId","Id");b.HasIndex(x=>x.CompanyId);} }
internal sealed class MarketingAttributionTouchConfiguration:IEntityTypeConfiguration<MarketingAttributionTouch>{public void Configure(EntityTypeBuilder<MarketingAttributionTouch>b){MarketingMeasurementConfiguration.I(b,"marketing_attribution_touches");b.Property(x=>x.SubjectType).HasColumnName("subject_type").HasMaxLength(80);b.Property(x=>x.SubjectId).HasColumnName("subject_id");b.Property(x=>x.TouchType).HasColumnName("touch_type").HasMaxLength(60);b.Property(x=>x.Channel).HasColumnName("channel").HasMaxLength(60);b.Property(x=>x.SourceReference).HasColumnName("source_reference").HasMaxLength(500);b.Property(x=>x.SourceVersion).HasColumnName("source_version");b.Property(x=>x.OccurredUtc).HasColumnName("occurred_at");b.Property(x=>x.Cost).HasColumnName("cost").HasPrecision(19,4);b.Property(x=>x.Currency).HasColumnName("currency").HasMaxLength(8);b.Property(x=>x.EvidenceJson).HasColumnName("evidence_json").HasColumnType("nvarchar(max)");b.Property(x=>x.IdempotencyKey).HasColumnName("idempotency_key").HasMaxLength(220);b.Property(x=>x.CreatedUtc).HasColumnName("created_at");b.HasIndex(x=>new{x.CompanyId,x.IdempotencyKey}).IsUnique();b.HasIndex(x=>new{x.CompanyId,x.SubjectType,x.SubjectId,x.OccurredUtc});}}
internal sealed class MarketingAttributionModelDefinitionConfiguration:IEntityTypeConfiguration<MarketingAttributionModelDefinition>{public void Configure(EntityTypeBuilder<MarketingAttributionModelDefinition>b){MarketingMeasurementConfiguration.I(b,"marketing_attribution_models");b.Property(x=>x.Name).HasColumnName("name").HasMaxLength(160);b.Property(x=>x.ModelType).HasColumnName("model_type").HasMaxLength(40);b.Property(x=>x.Version).HasColumnName("version");b.Property(x=>x.RulesJson).HasColumnName("rules_json").HasColumnType("nvarchar(max)");b.Property(x=>x.Limitations).HasColumnName("limitations").HasMaxLength(2000);b.Property(x=>x.LookbackDays).HasColumnName("lookback_days");b.Property(x=>x.IdempotencyKey).HasColumnName("idempotency_key").HasMaxLength(220);b.Property(x=>x.CreatedUtc).HasColumnName("created_at");b.HasIndex(x=>new{x.CompanyId,x.IdempotencyKey}).IsUnique();b.HasIndex(x=>new{x.CompanyId,x.Name,x.Version}).IsUnique();}}
internal sealed class MarketingAttributionAllocationConfiguration:IEntityTypeConfiguration<MarketingAttributionAllocation>{public void Configure(EntityTypeBuilder<MarketingAttributionAllocation>b){MarketingMeasurementConfiguration.I(b,"marketing_attribution_allocations");b.Property(x=>x.MarketingAttributionResultId).HasColumnName("result_id");b.Property(x=>x.MarketingAttributionTouchId).HasColumnName("touch_id");b.Property(x=>x.Weight).HasColumnName("weight").HasPrecision(8,7);b.Property(x=>x.AttributedValue).HasColumnName("attributed_value").HasPrecision(19,4);b.Property(x=>x.EvidenceVersion).HasColumnName("evidence_version").HasMaxLength(200);b.Property(x=>x.CreatedUtc).HasColumnName("created_at");b.HasIndex(x=>new{x.CompanyId,x.MarketingAttributionResultId,x.MarketingAttributionTouchId}).IsUnique();}}
internal sealed class MarketingExperimentExposureConfiguration:IEntityTypeConfiguration<MarketingExperimentExposure>{public void Configure(EntityTypeBuilder<MarketingExperimentExposure>b){MarketingMeasurementConfiguration.I(b,"marketing_experiment_exposures");b.Property(x=>x.MarketingExperimentId).HasColumnName("experiment_id");b.Property(x=>x.SubjectReference).HasColumnName("subject_reference").HasMaxLength(200);b.Property(x=>x.Variant).HasColumnName("variant").HasMaxLength(80);b.Property(x=>x.AssignmentKey).HasColumnName("assignment_key").HasMaxLength(220);b.Property(x=>x.ExposedUtc).HasColumnName("exposed_at");b.Property(x=>x.EvidenceJson).HasColumnName("evidence_json").HasColumnType("nvarchar(max)");b.HasIndex(x=>new{x.CompanyId,x.MarketingExperimentId,x.AssignmentKey}).IsUnique();}}
internal sealed class MarketingExperimentDecisionRecordConfiguration:IEntityTypeConfiguration<MarketingExperimentDecisionRecord>{public void Configure(EntityTypeBuilder<MarketingExperimentDecisionRecord>b){MarketingMeasurementConfiguration.I(b,"marketing_experiment_decisions");b.Property(x=>x.MarketingExperimentId).HasColumnName("experiment_id");b.Property(x=>x.Decision).HasColumnName("decision").HasMaxLength(60);b.Property(x=>x.SampleSize).HasColumnName("sample_size");b.Property(x=>x.ContaminationRate).HasColumnName("contamination_rate").HasPrecision(6,5);b.Property(x=>x.GuardrailBreached).HasColumnName("guardrail_breached");b.Property(x=>x.CausalEligible).HasColumnName("causal_eligible");b.Property(x=>x.EvidenceJson).HasColumnName("evidence_json").HasColumnType("nvarchar(max)");b.Property(x=>x.Limitations).HasColumnName("limitations").HasMaxLength(2000);b.Property(x=>x.CreatedUtc).HasColumnName("created_at");b.HasIndex(x=>new{x.CompanyId,x.MarketingExperimentId}).IsUnique();}}
internal sealed class MarketingSegmentLearningProposalConfiguration:IEntityTypeConfiguration<MarketingSegmentLearningProposal>{public void Configure(EntityTypeBuilder<MarketingSegmentLearningProposal>b){MarketingMeasurementConfiguration.I(b,"marketing_segment_learning_proposals");b.Property(x=>x.MarketingCustomerSegmentVersionId).HasColumnName("segment_version_id");b.Property(x=>x.MetricsJson).HasColumnName("metrics_json").HasColumnType("nvarchar(max)");b.Property(x=>x.ProposedChangesJson).HasColumnName("proposed_changes_json").HasColumnType("nvarchar(max)");b.Property(x=>x.EvidenceJson).HasColumnName("evidence_json").HasColumnType("nvarchar(max)");b.Property(x=>x.Confidence).HasColumnName("confidence").HasPrecision(5,4);b.Property(x=>x.IdempotencyKey).HasColumnName("idempotency_key").HasMaxLength(220);b.Property(x=>x.Status).HasColumnName("status").HasMaxLength(40);b.Property(x=>x.CreatedUtc).HasColumnName("created_at");b.HasIndex(x=>new{x.CompanyId,x.IdempotencyKey}).IsUnique();b.HasIndex(x=>new{x.CompanyId,x.MarketingCustomerSegmentVersionId,x.CreatedUtc});}}
