using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using VirtualCompany.Domain.Entities;
using VirtualCompany.Domain.Enums;
namespace VirtualCompany.Infrastructure.Persistence;
internal sealed class SalesPresentationRunConfiguration:IEntityTypeConfiguration<SalesPresentationRun>
{
 public void Configure(EntityTypeBuilder<SalesPresentationRun>b){b.ToTable("sales_presentation_runs",t=>{t.HasCheckConstraint("CK_sales_presentation_runs_duration","duration_minutes BETWEEN 5 AND 480");t.HasCheckConstraint("CK_sales_presentation_runs_preparation","preparation_version >= 1 AND preparation_attempt_count >= 0");});b.HasKey(x=>x.Id);b.HasAlternateKey(x=>new{x.CompanyId,x.Id});
 b.Property(x=>x.Id).HasColumnName("id");b.Property(x=>x.CompanyId).HasColumnName("company_id");b.Property(x=>x.PresetVersionId).HasColumnName("preset_version_id");b.Property(x=>x.ContextType).HasColumnName("context_type").HasConversion(x=>x.ToStorageValue(),x=>SalesPresentationPresetEnumValues.ParseContextType(x)).HasMaxLength(32);b.Property(x=>x.ContextReference).HasColumnName("context_reference").HasMaxLength(100);b.Property(x=>x.MeetingSessionId).HasColumnName("meeting_session_id");b.Property(x=>x.PresenterAgentId).HasColumnName("presenter_agent_id");
 b.Property(x=>x.Goal).HasColumnName("goal").HasMaxLength(2000);b.Property(x=>x.Audience).HasColumnName("audience").HasMaxLength(1000);b.Property(x=>x.DurationMinutes).HasColumnName("duration_minutes");b.Property(x=>x.DemoScenario).HasColumnName("demo_scenario").HasMaxLength(2000);b.Property(x=>x.Language).HasColumnName("language").HasMaxLength(20);b.Property(x=>x.ControlMode).HasColumnName("control_mode").HasMaxLength(20);b.Property(x=>x.GoalOverridden).HasColumnName("goal_overridden");b.Property(x=>x.AudienceOverridden).HasColumnName("audience_overridden");b.Property(x=>x.DurationOverridden).HasColumnName("duration_overridden");b.Property(x=>x.DemoScenarioOverridden).HasColumnName("demo_scenario_overridden");b.Property(x=>x.PresenterOverridden).HasColumnName("presenter_overridden");
 b.Property(x=>x.ClientRequestId).HasColumnName("client_request_id");b.Property(x=>x.ContextCustomerCompanyId).HasColumnName("context_customer_company_id");b.Property(x=>x.ContextContactId).HasColumnName("context_contact_id");b.Property(x=>x.ContextLeadId).HasColumnName("context_lead_id");b.Property(x=>x.ContextDealId).HasColumnName("context_deal_id");b.Property(x=>x.RuntimeStrategy).HasColumnName("runtime_strategy").HasMaxLength(32).HasDefaultValue("meeting_session");
 b.Property(x=>x.PreparationStatus).HasColumnName("preparation_status").HasConversion(x=>x.ToStorageValue(),x=>SalesPresentationPresetEnumValues.ParseRunStatus(x)).HasMaxLength(24);b.Property(x=>x.ReadinessBlockersJson).HasColumnName("readiness_blockers_json").HasColumnType("nvarchar(max)");b.Property(x=>x.PreparationVersion).HasColumnName("preparation_version");b.Property(x=>x.PreparationAttemptCount).HasColumnName("preparation_attempt_count");b.Property(x=>x.CanRetry).HasColumnName("can_retry");b.Property(x=>x.FailureCode).HasColumnName("failure_code").HasMaxLength(100);b.Property(x=>x.FailureSummary).HasColumnName("failure_summary").HasMaxLength(1000);b.Property(x=>x.PreparationStartedUtc).HasColumnName("preparation_started_at");b.Property(x=>x.PreparedUtc).HasColumnName("prepared_at");b.Property(x=>x.FailedUtc).HasColumnName("failed_at");b.Property(x=>x.CompatibilityDeckId).HasColumnName("compatibility_deck_id");b.Property(x=>x.IsActive).HasColumnName("is_active");b.Property(x=>x.CreatedByUserId).HasColumnName("created_by_user_id");b.Property(x=>x.UpdatedByUserId).HasColumnName("updated_by_user_id");b.Property(x=>x.CreatedUtc).HasColumnName("created_at");b.Property(x=>x.UpdatedUtc).HasColumnName("updated_at");b.Property(x=>x.ConcurrencyVersion).HasColumnName("concurrency_version").HasDefaultValue(1L).IsConcurrencyToken();
 b.HasIndex(x=>new{x.CompanyId,x.MeetingSessionId,x.IsActive}).IsUnique().HasFilter("[is_active] = CAST(1 AS bit) AND [meeting_session_id] IS NOT NULL");b.HasIndex(x=>new{x.CompanyId,x.PresetVersionId});b.HasIndex(x=>new{x.CompanyId,x.PreparationStatus,x.PreparationStartedUtc});
 b.HasIndex(x=>new{x.CompanyId,x.ClientRequestId}).IsUnique().HasFilter("[client_request_id] IS NOT NULL");
 b.HasOne<CustomerCompany>().WithMany().HasForeignKey(x=>new{x.CompanyId,x.ContextCustomerCompanyId}).HasPrincipalKey(x=>new{x.CompanyId,x.Id}).OnDelete(DeleteBehavior.Restrict);
 b.HasOne<Contact>().WithMany().HasForeignKey(x=>new{x.CompanyId,x.ContextContactId}).HasPrincipalKey(x=>new{x.CompanyId,x.Id}).OnDelete(DeleteBehavior.Restrict);
 b.HasOne<Lead>().WithMany().HasForeignKey(x=>new{x.CompanyId,x.ContextLeadId}).HasPrincipalKey(x=>new{x.CompanyId,x.Id}).OnDelete(DeleteBehavior.Restrict);
 b.HasOne<Deal>().WithMany().HasForeignKey(x=>new{x.CompanyId,x.ContextDealId}).HasPrincipalKey(x=>new{x.CompanyId,x.Id}).OnDelete(DeleteBehavior.Restrict);
 b.HasOne(x=>x.PresetVersion).WithMany().HasForeignKey(nameof(SalesPresentationRun.CompanyId),nameof(SalesPresentationRun.PresetVersionId)).HasPrincipalKey(nameof(SalesPresentationPresetVersion.CompanyId),nameof(SalesPresentationPresetVersion.Id)).OnDelete(DeleteBehavior.Restrict);b.HasOne(x=>x.MeetingSession).WithMany().HasForeignKey(nameof(SalesPresentationRun.CompanyId),nameof(SalesPresentationRun.MeetingSessionId)).HasPrincipalKey(nameof(SalesMeetingSession.CompanyId),nameof(SalesMeetingSession.Id)).OnDelete(DeleteBehavior.Restrict);b.HasOne(x=>x.PresenterAgent).WithMany().HasForeignKey(nameof(SalesPresentationRun.CompanyId),nameof(SalesPresentationRun.PresenterAgentId)).HasPrincipalKey(nameof(Agent.CompanyId),nameof(Agent.Id)).OnDelete(DeleteBehavior.Restrict);}
}
