using A=VirtualCompany.Application.Orchestration;
using Ap=VirtualCompany.Application.Approvals;
using System.Net;
using System.Net.Http.Json;
using Microsoft.EntityFrameworkCore;
using VirtualCompany.Domain.Entities;
namespace VirtualCompany.Api.Tests;
public sealed class AnnualPlanningIntegrationTests
{
 [Fact]public async Task Draft_review_canonical_approval_then_revision_preserves_approved_targets_owners_milestones_and_budgets(){using var f=new TestWebApplicationFactory(new SupportQualityFixture.Clock());var s=await AnnualPlanningFixture.Seed(f);using var h=s.Client(f);var draft=await AnnualPlanningFixture.Save(h,s);Assert.True(draft.CanReview);Assert.Equal(0,draft.Plan.Objectives.Single().Baseline);Assert.Equal(s.Quarter.Actual,draft.Plan.Objectives.Single().ProgressPercent);var reviewed=await AnnualPlanningFixture.Read<A.AnnualPlanDocument>(await h.PostAsJsonAsync(s.Root+$"/versions/{draft.Summary.Id}/review",new A.ReviewAnnualPlan(draft.Summary.StateRevision,draft.Plan.Fingerprint)));Assert.Equal("reviewed",reviewed.Summary.Status);Assert.NotNull(reviewed.Summary.ApprovalId);var root=$"/api/companies/{s.Quarter.Company.Company}/approvals/{reviewed.Summary.ApprovalId}";var ap=await AnnualPlanningFixture.Read<Ap.ApprovalRequestDto>(await h.GetAsync(root));Assert.True(ap.Review!.CanDecide);Assert.Contains(ap.Review.Evidence,x=>x.Href.Contains(draft.Summary.Id.ToString()));await AnnualPlanningFixture.Read<Ap.ApprovalDecisionResultDto>(await h.PostAsJsonAsync(root+"/decisions",new Ap.ApprovalDecisionCommand(ap.Id,"approve",Comment:"Annual governance accepted",ClientRequestId:Guid.NewGuid(),ReviewToken:ap.Review.Token)));var approved=await AnnualPlanningFixture.Read<A.AnnualPlanDocument>(await h.PostAsync(s.Root+$"/versions/{draft.Summary.Id}/open",null));Assert.Equal("approved",approved.Summary.Status);var changed=s.Input with{Objectives=[s.Input.Objectives[0] with{Target=120,OwnerUserId=s.Quarter.Company.Manager,Milestones=s.Input.Objectives[0].Milestones.Select(m=>m.Quarter==3?m with{Title="Revised Q3 checkpoint"}:m).ToArray()}],Allocations=[s.Input.Allocations[0] with{Title="Revised service investment"}]};var next=await AnnualPlanningFixture.Save(h,s,changed,approved);Assert.Equal("draft",next.Summary.Status);Assert.Contains(next.Changes,x=>x.Contains("100 → 120"));Assert.Contains(next.Changes,x=>x.Contains("milestones changed"));Assert.Contains(next.Changes,x=>x.Contains("allocations changed"));var old=await AnnualPlanningFixture.Read<A.AnnualPlanDocument>(await h.PostAsync(s.Root+$"/versions/{approved.Summary.Id}/open",null));Assert.Equal(100,old.Plan.Objectives[0].Input.Target);Assert.Equal("approved",old.Summary.Status);await f.SeedAsync(async db=>{Assert.Empty(await db.PaymentInstructions.IgnoreQueryFilters().Where(x=>x.CompanyId==s.Quarter.Company.Company).ToListAsync());Assert.Equal(1000,(await db.Budgets.IgnoreQueryFilters().SingleAsync(x=>x.Id==s.BudgetId)).Amount);});}
 [Fact]public async Task Incomplete_allocations_block_review_and_invalid_accountability_units_periods_and_currency_fail(){using var f=new TestWebApplicationFactory(new SupportQualityFixture.Clock());var s=await AnnualPlanningFixture.Seed(f);using var h=s.Client(f);var unbalanced=s.Input with{Allocations=[s.Input.Allocations[0] with{Amount=900}]};var d=await AnnualPlanningFixture.Save(h,s,unbalanced);Assert.False(d.CanReview);Assert.Equal(HttpStatusCode.BadRequest,(await h.PostAsJsonAsync(s.Root+$"/versions/{d.Summary.Id}/review",new A.ReviewAnnualPlan(1,d.Plan.Fingerprint))).StatusCode);foreach(var bad in new[]{s.Input with{Objectives=[s.Input.Objectives[0] with{OwnerUserId=Guid.NewGuid()}]},s.Input with{Objectives=[s.Input.Objectives[0] with{Unit="SEK"}]},s.Input with{Objectives=[s.Input.Objectives[0] with{Milestones=[new(1,"Wrong period",new DateTime(2027,1,1,0,0,0,DateTimeKind.Utc))]}]}})Assert.Equal(HttpStatusCode.BadRequest,(await h.PostAsJsonAsync(s.Root+"/preview",bad)).StatusCode);await f.SeedAsync(async db=>{var b=await db.Budgets.IgnoreQueryFilters().SingleAsync(x=>x.Id==s.BudgetId);b.Update(b.FinanceAccountId,b.PeriodStartUtc,b.Version,b.Amount,"EUR");});Assert.Equal(HttpStatusCode.BadRequest,(await h.PostAsJsonAsync(s.Root+"/preview",s.Input)).StatusCode);}
 [Fact]public async Task Source_budget_change_stales_canonical_approval_and_generic_approval_cannot_bypass_draft_lifecycle(){using var f=new TestWebApplicationFactory(new SupportQualityFixture.Clock());var s=await AnnualPlanningFixture.Seed(f);using var h=s.Client(f);var d=await AnnualPlanningFixture.Save(h,s);Assert.Equal(HttpStatusCode.Forbidden,(await h.PostAsync($"/api/companies/{s.Quarter.Company.Company}/approvals",JsonContent.Create(new Ap.CreateApprovalRequestCommand("annual_plan_version",d.Summary.Id,"user",s.Quarter.Company.Owner,"annual_plan_governance",new Dictionary<string,System.Text.Json.Nodes.JsonNode?>{{"annualFingerprint",System.Text.Json.Nodes.JsonValue.Create(d.Plan.Fingerprint)}},"manager")))).StatusCode);var r=await AnnualPlanningFixture.Read<A.AnnualPlanDocument>(await h.PostAsJsonAsync(s.Root+$"/versions/{d.Summary.Id}/review",new A.ReviewAnnualPlan(1,d.Plan.Fingerprint)));var root=$"/api/companies/{s.Quarter.Company.Company}/approvals/{r.Summary.ApprovalId}";var ap=await AnnualPlanningFixture.Read<Ap.ApprovalRequestDto>(await h.GetAsync(root));await f.SeedAsync(async db=>{var b=await db.Budgets.IgnoreQueryFilters().SingleAsync(x=>x.Id==s.BudgetId);b.Update(b.FinanceAccountId,b.PeriodStartUtc,b.Version,1100,b.Currency);});Assert.Equal(HttpStatusCode.Conflict,(await h.PostAsJsonAsync(root+"/decisions",new Ap.ApprovalDecisionCommand(ap.Id,"approve",ReviewToken:ap.Review!.Token))).StatusCode);var retained=await AnnualPlanningFixture.Read<A.AnnualPlanDocument>(await h.PostAsync(s.Root+$"/versions/{d.Summary.Id}/open",null));Assert.Equal("stale",retained.Summary.Status);Assert.Equal(1000,retained.Plan.BudgetTotal);}
 [Fact]public async Task Stale_revision_and_foreign_reads_writes_reject_and_manager_does_not_gain_private_baseline(){using var f=new TestWebApplicationFactory(new SupportQualityFixture.Clock());var s=await AnnualPlanningFixture.Seed(f);using var h=s.Client(f);var p=await AnnualPlanningFixture.Read<A.AnnualPlanPreview>(await h.PostAsJsonAsync(s.Root+"/preview",s.Input));var cmd=new A.SaveAnnualPlan(s.Input,null,0,Guid.NewGuid(),p.Fingerprint);var d=await AnnualPlanningFixture.Read<A.AnnualPlanDocument>(await h.PostAsJsonAsync(s.Root+"/versions",cmd));var repeat=await AnnualPlanningFixture.Read<A.AnnualPlanDocument>(await h.PostAsJsonAsync(s.Root+"/versions",cmd));Assert.Equal(d.Summary.Id,repeat.Summary.Id);Assert.Equal(HttpStatusCode.Conflict,(await h.PostAsJsonAsync(s.Root+"/versions",cmd with{RequestId=Guid.NewGuid()})).StatusCode);using var foreign=s.Client(f,"p19-foreign");Assert.Contains((await foreign.PostAsync(s.Root+$"/versions/{d.Summary.Id}/open",null)).StatusCode,new[]{HttpStatusCode.Forbidden,HttpStatusCode.Unauthorized});using var manager=s.Client(f,"p19-manager");Assert.Equal(HttpStatusCode.Forbidden,(await manager.PostAsync(s.Root+$"/versions/{d.Summary.Id}/open",null)).StatusCode);}
 [Fact]public async Task Configured_fiscal_year_retains_half_open_timezone_boundaries(){using var f=new TestWebApplicationFactory(new SupportQualityFixture.Clock());var s=await AnnualPlanningFixture.Seed(f);using var h=s.Client(f);var o=await AnnualPlanningFixture.Read<A.AnnualPlanningOptions>(await h.GetAsync(s.Root+"/options?fiscalYear=2026"));Assert.Equal(new DateTime(2025,12,31,23,0,0,DateTimeKind.Utc),o.Period.StartUtc);Assert.Equal(new DateTime(2026,12,31,23,0,0,DateTimeKind.Utc),o.Period.EndUtc);Assert.Equal("SEK",o.Period.Currency);}
}




