using System.Reflection;using Microsoft.EntityFrameworkCore.Migrations;using Microsoft.EntityFrameworkCore.Migrations.Operations;using VirtualCompany.Domain.Entities;using VirtualCompany.Domain.Enums;using VirtualCompany.Persistence.Migrations.Persistence.Migrations;
namespace VirtualCompany.Api.Tests;
public sealed class SalesPresentationRunTests
{
 [Fact]public void Run_preserves_version_overrides_and_exact_runtime_binding(){var now=DateTime.UtcNow;var run=new SalesPresentationRun(Guid.NewGuid(),Guid.NewGuid(),Guid.NewGuid(),Guid.NewGuid(),Guid.NewGuid(),"Meeting goal","Executive team",45,"Demo","en","assisted",true,false,true,false,true,Guid.NewGuid(),now);run.BeginPreparation(run.CreatedByUserId,now.AddSeconds(1));var deck=Guid.NewGuid();run.CompletePreparation(deck,false,null,run.CreatedByUserId,now.AddSeconds(2));Assert.Equal(SalesPresentationRunPreparationStatus.Ready,run.PreparationStatus);Assert.Equal(deck,run.CompatibilityDeckId);Assert.True(run.GoalOverridden);Assert.True(run.DurationOverridden);Assert.True(run.PresenterOverridden);Assert.Equal(1,run.PreparationAttemptCount);}
 [Fact]public void Retry_is_bounded_and_increments_preparation_version(){var now=DateTime.UtcNow;var actor=Guid.NewGuid();var run=new SalesPresentationRun(Guid.NewGuid(),Guid.NewGuid(),Guid.NewGuid(),Guid.NewGuid(),Guid.NewGuid(),"Goal","Audience",30,null,"sv-se","manual",false,false,false,false,false,actor,now);Assert.Throws<InvalidOperationException>(()=>run.QueueRetry(actor,now));run.BeginPreparation(actor,now);run.FailPreparation("temporary","Temporary grounding failure.",true,actor,now);run.QueueRetry(actor,now);Assert.Equal(SalesPresentationRunPreparationStatus.Pending,run.PreparationStatus);Assert.Equal(2,run.PreparationVersion);}
 [Fact]public void Compatibility_deck_can_only_be_bound_before_processing(){var now=DateTime.UtcNow;var deck=new SalesPresentationDeck(Guid.NewGuid(),Guid.NewGuid(),Guid.NewGuid(),Guid.NewGuid(),1,"Title","deck.pptx","application/octet-stream",100,new string('a',64),"safe/deck.pptx",null,Guid.NewGuid(),now);var run=Guid.NewGuid();var asset=Guid.NewGuid();deck.BindToPresentationRun(run,asset);Assert.Equal(run,deck.PresentationRunId);Assert.Equal(asset,deck.PresetAssetId);Assert.Throws<InvalidOperationException>(()=>deck.BindToPresentationRun(Guid.NewGuid(),asset));}
 [Fact]public void Run_artifacts_are_explicitly_context_owned(){var company=Guid.NewGuid();var run=Guid.NewGuid();var artifact=new SalesPresentationRunArtifact(Guid.NewGuid(),company,run,1,SalesPresentationRunArtifactType.MissingEvidence,"No contact is linked.","needs_review","sales_meeting_session:1",null,0,null,DateTime.UtcNow);Assert.Equal(company,artifact.CompanyId);Assert.Equal(run,artifact.RunId);Assert.Equal(SalesPresentationRunArtifactType.MissingEvidence,artifact.Type);}
}
public sealed class SalesPresentationRunMigrationTests
{
 [Fact]public void Migration_is_additive_and_enforces_active_run_and_tenant_foreign_keys(){var operations=Up(new AddSalesPresentationRuns());Assert.DoesNotContain(operations,x=>x is DropColumnOperation or DropTableOperation);var tables=operations.OfType<CreateTableOperation>().ToDictionary(x=>x.Name);Assert.Contains("sales_presentation_runs",tables.Keys);Assert.Contains("sales_presentation_run_artifacts",tables.Keys);Assert.Contains(tables["sales_presentation_runs"].ForeignKeys,x=>x.PrincipalTable=="sales_presentation_preset_versions"&&x.Columns.SequenceEqual(["company_id","preset_version_id"]));Assert.Contains(tables["sales_presentation_runs"].ForeignKeys,x=>x.PrincipalTable=="sales_meeting_sessions"&&x.Columns.SequenceEqual(["company_id","meeting_session_id"]));Assert.Contains(operations.OfType<CreateIndexOperation>(),x=>x.Table=="sales_presentation_runs"&&x.IsUnique&&x.Columns.SequenceEqual(["company_id","meeting_session_id","is_active"]));Assert.Contains(operations.OfType<AddColumnOperation>(),x=>x.Table=="sales_presentation_decks"&&x.Name=="presentation_run_id");}
 private static IReadOnlyList<MigrationOperation>Up(Migration migration){var builder=new MigrationBuilder("Microsoft.EntityFrameworkCore.SqlServer");migration.GetType().GetMethod("Up",BindingFlags.Instance|BindingFlags.NonPublic)!.Invoke(migration,[builder]);return builder.Operations;}
}
