using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using VirtualCompany.Api.ProblemHandling;using VirtualCompany.Application.Auth;using VirtualCompany.Application.Authorization;using VirtualCompany.Application.Sales;using VirtualCompany.Infrastructure.Tenancy;
namespace VirtualCompany.Api.Controllers;
[ApiController][Route("api/sales/meeting-sessions/{sessionId:guid}/presentation-run")][Authorize(Policy=CompanyPolicies.CompanyMember)][RequireCompanyContext]
public sealed class SalesPresentationRunsController(ISalesPresentationRunService runs,ICompanyContextAccessor context):ControllerBase
{
 [HttpGet]public async Task<ActionResult<SalesPresentationRunDto>>Get(Guid sessionId,CancellationToken ct){var value=await runs.GetActiveAsync(Company(),Actor(),sessionId,ct);return value is null?NotFound():Ok(value);}
 [HttpPost]public Task<ActionResult<SalesPresentationRunDto>>Apply(Guid sessionId,[FromBody]ApplySalesPresentationPresetRequest request,CancellationToken ct)=>Mutate(async()=>await runs.ApplyAsync(Company(),Actor(),sessionId,request.ToCommand(),HttpContext.TraceIdentifier,ct));
 [HttpPost("/api/sales/meeting-invitations/{invitationId:guid}/presentation-run")]
 public Task<ActionResult<SalesPresentationRunDto>> ApplyToInvitation(Guid invitationId,[FromBody]ApplySalesPresentationPresetRequest request,CancellationToken ct)=>Mutate(()=>runs.ApplyToInvitationAsync(Company(),Actor(),invitationId,request.ToCommand(),HttpContext.TraceIdentifier,ct));
 [HttpPost("{runId:guid}/retry")]public Task<ActionResult<SalesPresentationRunDto>>Retry(Guid sessionId,Guid runId,[FromBody]RetrySalesPresentationRunRequest request,CancellationToken ct)=>Mutate(async()=>await runs.RetryAsync(Company(),Actor(),sessionId,runId,request.ExpectedVersion,HttpContext.TraceIdentifier,ct));
 [HttpGet("{runId:guid}/compare/{targetVersionId:guid}")]public async Task<ActionResult<SalesPresentationRunVersionComparisonDto>>Compare(Guid sessionId,Guid runId,Guid targetVersionId,CancellationToken ct){var value=await runs.CompareVersionAsync(Company(),Actor(),sessionId,runId,targetVersionId,ct);return value is null?NotFound():Ok(value);}
 [HttpPost("save-as-preset")]public async Task<ActionResult<SalesPresentationPresetDto>>Save(Guid sessionId,[FromBody]SaveMeetingSetupAsPresetRequest request,CancellationToken ct){try{var value=await runs.SaveAsPresetAsync(Company(),Actor(),sessionId,request.DeckId,request.Name,request.Description,HttpContext.TraceIdentifier,ct);return value is null?NotFound():Created($"api/sales/presentation-presets/{value.Id:D}",value);}catch(SalesPresentationPresetValidationException e){return BadRequest(StableProblemDetails.CreateValidation(HttpContext,e.Errors,ApiProblemCodes.SalesRequestInvalid));}catch(SalesPresentationPresetConflictException e){return ConflictResult(e);}}
 private async Task<ActionResult<SalesPresentationRunDto>>Mutate(Func<Task<SalesPresentationRunDto?>> action){try{var value=await action();return value is null?NotFound():Ok(value);}catch(SalesPresentationPresetValidationException e){return BadRequest(StableProblemDetails.CreateValidation(HttpContext,e.Errors,ApiProblemCodes.SalesRequestInvalid));}catch(SalesPresentationPresetConflictException e){return ConflictResult(e);}}
 private ObjectResult ConflictResult(SalesPresentationPresetConflictException e)=>Conflict(StableProblemDetails.Create(HttpContext,StatusCodes.Status409Conflict,e.Code,"Presentation run conflict",e.Message));private Guid Company()=>context.CompanyId is{}id&&id!=Guid.Empty?id:throw new UnauthorizedAccessException("A resolved company is required.");private Guid Actor()=>context.UserId is{}id&&id!=Guid.Empty?id:throw new UnauthorizedAccessException("A resolved user is required.");
}
public sealed record ApplySalesPresentationPresetRequest(Guid? PresetId,Guid? PresetVersionId,Guid? PresenterAgentId,string? Goal,string? Audience,int? DurationMinutes,string? DemoScenario,string? Language,string? ControlMode,bool ReplaceActive,long? ExpectedActiveRunVersion){public ApplySalesPresentationPresetCommand ToCommand()=>new(PresetId,PresetVersionId,PresenterAgentId,Goal,Audience,DurationMinutes,DemoScenario,Language,ControlMode,ReplaceActive,ExpectedActiveRunVersion);}public sealed record RetrySalesPresentationRunRequest(long ExpectedVersion);public sealed record SaveMeetingSetupAsPresetRequest(Guid DeckId,string Name,string? Description);
