using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;
using VirtualCompany.Infrastructure.Persistence;

#nullable disable

namespace VirtualCompany.Persistence.Migrations.Persistence.Migrations;

[DbContext(typeof(VirtualCompanyDbContext))]
[Migration("20260830210000_AddComplianceObligationCalendar")]
public sealed class AddComplianceObligationCalendar : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AddColumn<DateOnly>(name: "due_date", table: "vat_filing_periods", type: "date", nullable: true);
        migrationBuilder.CreateTable(name: "compliance_command_receipts", columns: table => new
        {
            Id=table.Column<Guid>(type:"uniqueidentifier",nullable:false), CompanyId=table.Column<Guid>(type:"uniqueidentifier",nullable:false), IdempotencyKey=table.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:false), PayloadHash=table.Column<string>(type:"nvarchar(64)",maxLength:64,nullable:false), InstanceId=table.Column<Guid>(type:"uniqueidentifier",nullable:false), CreatedUtc=table.Column<DateTime>(type:"datetime2",nullable:false)
        },constraints:table=>table.PrimaryKey("PK_compliance_command_receipts",x=>x.Id));
        migrationBuilder.CreateTable(name:"compliance_obligation_instances",columns:table=>new
        {
            Id=table.Column<Guid>(type:"uniqueidentifier",nullable:false),CompanyId=table.Column<Guid>(type:"uniqueidentifier",nullable:false),DefinitionKey=table.Column<string>(type:"nvarchar(100)",maxLength:100,nullable:false),Title=table.Column<string>(type:"nvarchar(240)",maxLength:240,nullable:false),Jurisdiction=table.Column<string>(type:"nvarchar(64)",maxLength:64,nullable:false),PolicyPackKey=table.Column<string>(type:"nvarchar(100)",maxLength:100,nullable:false),PolicyPackVersion=table.Column<string>(type:"nvarchar(64)",maxLength:64,nullable:false),PolicyPackDefinitionHash=table.Column<string>(type:"nvarchar(128)",maxLength:128,nullable:false),DueDateRule=table.Column<string>(type:"nvarchar(160)",maxLength:160,nullable:false),DueDate=table.Column<DateOnly>(type:"date",nullable:false),OwnerUserId=table.Column<Guid>(type:"uniqueidentifier",nullable:false),Status=table.Column<string>(type:"nvarchar(40)",maxLength:40,nullable:false),SubmissionMode=table.Column<string>(type:"nvarchar(64)",maxLength:64,nullable:false),VatFilingPeriodId=table.Column<Guid>(type:"uniqueidentifier",nullable:false),VatReturnId=table.Column<Guid>(type:"uniqueidentifier",nullable:true),AccountingCloseTaskId=table.Column<Guid>(type:"uniqueidentifier",nullable:true),CorrectionOfInstanceId=table.Column<Guid>(type:"uniqueidentifier",nullable:true),CorrectedByInstanceId=table.Column<Guid>(type:"uniqueidentifier",nullable:true),SourceHash=table.Column<string>(type:"nvarchar(128)",maxLength:128,nullable:false),ExportReference=table.Column<string>(type:"nvarchar(500)",maxLength:500,nullable:true),ExportChecksum=table.Column<string>(type:"nvarchar(128)",maxLength:128,nullable:true),GeneratedByUserId=table.Column<Guid>(type:"uniqueidentifier",nullable:false),PreparedByUserId=table.Column<Guid>(type:"uniqueidentifier",nullable:true),ReviewedByUserId=table.Column<Guid>(type:"uniqueidentifier",nullable:true),ApprovedByUserId=table.Column<Guid>(type:"uniqueidentifier",nullable:true),CreatedUtc=table.Column<DateTime>(type:"datetime2",nullable:false),UpdatedUtc=table.Column<DateTime>(type:"datetime2",nullable:false),Version=table.Column<long>(type:"bigint",nullable:false)
        },constraints:table=>{table.PrimaryKey("PK_compliance_obligation_instances",x=>x.Id);table.ForeignKey("FK_compliance_obligation_instances_accounting_close_tasks_AccountingCloseTaskId",x=>x.AccountingCloseTaskId,"accounting_close_tasks","Id",onDelete:ReferentialAction.Restrict);table.ForeignKey("FK_compliance_obligation_instances_vat_filing_periods_VatFilingPeriodId",x=>x.VatFilingPeriodId,"vat_filing_periods","id",onDelete:ReferentialAction.Restrict);table.ForeignKey("FK_compliance_obligation_instances_vat_returns_VatReturnId",x=>x.VatReturnId,"vat_returns","id",onDelete:ReferentialAction.Restrict);});
        migrationBuilder.CreateTable(name:"compliance_authority_acknowledgements",columns:table=>new{Id=table.Column<Guid>(type:"uniqueidentifier",nullable:false),CompanyId=table.Column<Guid>(type:"uniqueidentifier",nullable:false),InstanceId=table.Column<Guid>(type:"uniqueidentifier",nullable:false),Kind=table.Column<string>(type:"nvarchar(24)",maxLength:24,nullable:false),Reference=table.Column<string>(type:"nvarchar(500)",maxLength:500,nullable:false),ContentHash=table.Column<string>(type:"nvarchar(128)",maxLength:128,nullable:false),ActorUserId=table.Column<Guid>(type:"uniqueidentifier",nullable:false),OccurredUtc=table.Column<DateTime>(type:"datetime2",nullable:false)},constraints:table=>{table.PrimaryKey("PK_compliance_authority_acknowledgements",x=>x.Id);table.ForeignKey("FK_compliance_authority_acknowledgements_compliance_obligation_instances_InstanceId",x=>x.InstanceId,"compliance_obligation_instances","Id",onDelete:ReferentialAction.Cascade);});
        migrationBuilder.CreateTable(name:"compliance_obligation_history",columns:table=>new{Id=table.Column<Guid>(type:"uniqueidentifier",nullable:false),CompanyId=table.Column<Guid>(type:"uniqueidentifier",nullable:false),InstanceId=table.Column<Guid>(type:"uniqueidentifier",nullable:false),Action=table.Column<string>(type:"nvarchar(64)",maxLength:64,nullable:false),FromStatus=table.Column<string>(type:"nvarchar(40)",maxLength:40,nullable:false),ToStatus=table.Column<string>(type:"nvarchar(40)",maxLength:40,nullable:false),ActorUserId=table.Column<Guid>(type:"uniqueidentifier",nullable:false),SourceHash=table.Column<string>(type:"nvarchar(128)",maxLength:128,nullable:false),Reason=table.Column<string>(type:"nvarchar(1000)",maxLength:1000,nullable:true),OccurredUtc=table.Column<DateTime>(type:"datetime2",nullable:false)},constraints:table=>{table.PrimaryKey("PK_compliance_obligation_history",x=>x.Id);table.ForeignKey("FK_compliance_obligation_history_compliance_obligation_instances_InstanceId",x=>x.InstanceId,"compliance_obligation_instances","Id",onDelete:ReferentialAction.Cascade);});
        migrationBuilder.CreateTable(name:"compliance_reminders",columns:table=>new{Id=table.Column<Guid>(type:"uniqueidentifier",nullable:false),CompanyId=table.Column<Guid>(type:"uniqueidentifier",nullable:false),InstanceId=table.Column<Guid>(type:"uniqueidentifier",nullable:false),Kind=table.Column<string>(type:"nvarchar(32)",maxLength:32,nullable:false),EscalationLevel=table.Column<int>(type:"int",nullable:false),Status=table.Column<string>(type:"nvarchar(24)",maxLength:24,nullable:false),CreatedUtc=table.Column<DateTime>(type:"datetime2",nullable:false)},constraints:table=>{table.PrimaryKey("PK_compliance_reminders",x=>x.Id);table.ForeignKey("FK_compliance_reminders_compliance_obligation_instances_InstanceId",x=>x.InstanceId,"compliance_obligation_instances","Id",onDelete:ReferentialAction.Cascade);});
        migrationBuilder.CreateTable(name:"compliance_submission_evidence",columns:table=>new{Id=table.Column<Guid>(type:"uniqueidentifier",nullable:false),CompanyId=table.Column<Guid>(type:"uniqueidentifier",nullable:false),InstanceId=table.Column<Guid>(type:"uniqueidentifier",nullable:false),Reference=table.Column<string>(type:"nvarchar(500)",maxLength:500,nullable:false),ContentHash=table.Column<string>(type:"nvarchar(128)",maxLength:128,nullable:false),ActorUserId=table.Column<Guid>(type:"uniqueidentifier",nullable:false),SubmittedUtc=table.Column<DateTime>(type:"datetime2",nullable:false),ReviewStatus=table.Column<string>(type:"nvarchar(24)",maxLength:24,nullable:false),ReviewedByUserId=table.Column<Guid>(type:"uniqueidentifier",nullable:true),ReviewedUtc=table.Column<DateTime>(type:"datetime2",nullable:true)},constraints:table=>{table.PrimaryKey("PK_compliance_submission_evidence",x=>x.Id);table.ForeignKey("FK_compliance_submission_evidence_compliance_obligation_instances_InstanceId",x=>x.InstanceId,"compliance_obligation_instances","Id",onDelete:ReferentialAction.Cascade);});
        migrationBuilder.CreateIndex("IX_compliance_command_receipts_CompanyId_IdempotencyKey","compliance_command_receipts",new[]{"CompanyId","IdempotencyKey"},unique:true);
        migrationBuilder.CreateIndex("IX_compliance_obligation_instances_AccountingCloseTaskId","compliance_obligation_instances","AccountingCloseTaskId"); migrationBuilder.CreateIndex("IX_compliance_obligation_instances_VatFilingPeriodId","compliance_obligation_instances","VatFilingPeriodId"); migrationBuilder.CreateIndex("IX_compliance_obligation_instances_VatReturnId","compliance_obligation_instances","VatReturnId"); migrationBuilder.CreateIndex("IX_compliance_obligation_instances_CompanyId_DueDate_Status","compliance_obligation_instances",new[]{"CompanyId","DueDate","Status"}); migrationBuilder.CreateIndex("IX_compliance_obligation_instances_origin","compliance_obligation_instances",new[]{"CompanyId","DefinitionKey","VatFilingPeriodId"},unique:true,filter:"[CorrectionOfInstanceId] IS NULL"); migrationBuilder.CreateIndex("IX_compliance_obligation_instances_correction","compliance_obligation_instances",new[]{"CompanyId","CorrectionOfInstanceId"},unique:true,filter:"[CorrectionOfInstanceId] IS NOT NULL");
        migrationBuilder.CreateIndex("IX_compliance_authority_acknowledgements_InstanceId","compliance_authority_acknowledgements","InstanceId");migrationBuilder.CreateIndex("IX_compliance_authority_acknowledgements_CompanyId_InstanceId_Kind_ContentHash","compliance_authority_acknowledgements",new[]{"CompanyId","InstanceId","Kind","ContentHash"},unique:true); migrationBuilder.CreateIndex("IX_compliance_obligation_history_InstanceId","compliance_obligation_history","InstanceId");migrationBuilder.CreateIndex("IX_compliance_obligation_history_CompanyId_InstanceId_OccurredUtc","compliance_obligation_history",new[]{"CompanyId","InstanceId","OccurredUtc"}); migrationBuilder.CreateIndex("IX_compliance_reminders_InstanceId","compliance_reminders","InstanceId");migrationBuilder.CreateIndex("IX_compliance_reminders_CompanyId_InstanceId_Kind_EscalationLevel","compliance_reminders",new[]{"CompanyId","InstanceId","Kind","EscalationLevel"},unique:true); migrationBuilder.CreateIndex("IX_compliance_submission_evidence_InstanceId","compliance_submission_evidence","InstanceId");migrationBuilder.CreateIndex("IX_compliance_submission_evidence_CompanyId_InstanceId_ContentHash","compliance_submission_evidence",new[]{"CompanyId","InstanceId","ContentHash"},unique:true);
    }
    protected override void Down(MigrationBuilder migrationBuilder) { migrationBuilder.DropTable("compliance_authority_acknowledgements");migrationBuilder.DropTable("compliance_command_receipts");migrationBuilder.DropTable("compliance_obligation_history");migrationBuilder.DropTable("compliance_reminders");migrationBuilder.DropTable("compliance_submission_evidence");migrationBuilder.DropTable("compliance_obligation_instances");migrationBuilder.DropColumn("due_date","vat_filing_periods"); }
}
