<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VirtualCompany.Application\VirtualCompany.Application.csproj" />
    <ProjectReference Include="..\VirtualCompany.Domain\VirtualCompany.Domain.csproj" />
    <ProjectReference Include="..\VirtualCompany.Infrastructure.Platform\VirtualCompany.Infrastructure.Platform.csproj" />
    <ProjectReference Include="..\VirtualCompany.Persistence\VirtualCompany.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.14" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.14" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
