using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
namespace VirtualCompany.Web.Services;
public sealed class AnnualPlanningApiClient(ICompanyApiTransport transport,bool offline=false)
{
 public async Task<AnnualPlanningOptions> Options(Guid c,int year,CancellationToken ct){var r=await Send<AnnualPlanningOptions>(c,HttpMethod.Get,$"/options?fiscalYear={year}",null,ct);Check(r.Period.FiscalYear==year);return r;}
 public async Task<IReadOnlyList<AnnualPlanSummary>> History(Guid c,int year,CancellationToken ct){var r=await Send<IReadOnlyList<AnnualPlanSummary>>(c,HttpMethod.Get,$"/versions?fiscalYear={year}",null,ct);Check(r.All(x=>x.FiscalYear==year));return r;}
 public async Task<AnnualPlanPreview> Preview(Guid c,AnnualPlanInput input,CancellationToken ct){var r=await Send<AnnualPlanPreview>(c,HttpMethod.Post,"/preview",input,ct);Check(JsonSerializer.Serialize(r.Input)==JsonSerializer.Serialize(input));return r;}
 public async Task<AnnualPlanDocument> Save(Guid c,SaveAnnualPlan cmd,CancellationToken ct){var r=await Send<AnnualPlanDocument>(c,HttpMethod.Post,"/versions",cmd,ct);Check(r.Summary.PreviousId==cmd.PreviousId&&r.Summary.Version==cmd.ExpectedVersion+1&&r.Plan.Fingerprint==cmd.ExpectedFingerprint);return r;}
 public async Task<AnnualPlanDocument> Open(Guid c,Guid id,CancellationToken ct){var r=await Send<AnnualPlanDocument>(c,HttpMethod.Post,$"/versions/{id}/open",null,ct);Check(r.Summary.Id==id);return r;}
 public async Task<AnnualPlanDocument> Review(Guid c,Guid id,ReviewAnnualPlan cmd,CancellationToken ct){var r=await Send<AnnualPlanDocument>(c,HttpMethod.Post,$"/versions/{id}/review",cmd,ct);Check(r.Summary.Id==id&&r.Summary.Status=="reviewed"&&r.Summary.ApprovalId.HasValue);return r;}
 private static void Check(bool valid){if(!valid)throw new InvalidDataException("Annual response period or version differs from this request.");}
 private async Task<T> Send<T>(Guid c,HttpMethod method,string path,object? body,CancellationToken ct){if(offline||c==Guid.Empty)throw new InvalidOperationException("Choose a connected company before annual planning.");using var r=await transport.SendAsync(c,method,$"api/companies/{c}/planning/years{path}",body==null?null:JsonContent.Create(body),ct);if(r.StatusCode is HttpStatusCode.Unauthorized or HttpStatusCode.Forbidden)throw new TodayWorkspaceAccessException(r.StatusCode);if(!r.IsSuccessStatusCode){string? detail=null;try{using var j=JsonDocument.Parse(await r.Content.ReadAsStringAsync(ct));if(j.RootElement.TryGetProperty("detail",out var d))detail=d.GetString();}catch(JsonException){}throw new InvalidOperationException(detail??"Annual planning is unavailable. Reload current company and version.");}var v=await r.Content.ReadFromJsonAsync<T>(ct)??throw new InvalidDataException("Annual response empty.");var valid=v switch{AnnualPlanningOptions x=>x.CompanyId==c&&x.Period!=null&&x.Goals!=null&&x.Budgets!=null&&x.Owners!=null,AnnualPlanPreview x=>x.CompanyId==c&&x.Fingerprint?.Length==64&&x.Input!=null,AnnualPlanDocument x=>x.Summary.CompanyId==c&&x.Plan.CompanyId==c&&x.Plan.Fingerprint?.Length==64,IReadOnlyList<AnnualPlanSummary> x=>x.All(i=>i.CompanyId==c),_=>false};if(!valid)throw new InvalidDataException("Annual response context differs from this company.");return v;}
}
