using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace VirtualCompany.Web.Services;

public sealed class CompanyOperationApiClient(HttpClient http)
{
    private static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    public Task<List<CompanyGoalViewModel>> ListGoalsAsync(Guid companyId, CancellationToken ct = default) => GetAsync<List<CompanyGoalViewModel>>($"api/companies/{companyId:D}/operating/goals", ct);
    public Task<CompanyOperatingConfigurationViewModel> GetConfigurationAsync(Guid companyId, CancellationToken ct = default) => GetAsync<CompanyOperatingConfigurationViewModel>($"api/companies/{companyId:D}/operating/configuration", ct);
    public Task<List<OperatingCycleViewModel>> ListCyclesAsync(Guid companyId, CancellationToken ct = default) => GetAsync<List<OperatingCycleViewModel>>($"api/companies/{companyId:D}/operating/cycles?take=20", ct);
    public Task<List<OperatingDispatchViewModel>> ListDispatchesAsync(Guid companyId, CancellationToken ct = default) => GetAsync<List<OperatingDispatchViewModel>>($"api/companies/{companyId:D}/operating/dispatches?take=20", ct);
    public Task<List<OperatingEventViewModel>> ListEventsAsync(Guid companyId, CancellationToken ct = default) => GetAsync<List<OperatingEventViewModel>>($"api/companies/{companyId:D}/operating/events?take=20", ct);
    public Task<List<OperatingCycleRequestViewModel>> ListCycleRequestsAsync(Guid companyId, CancellationToken ct = default) => GetAsync<List<OperatingCycleRequestViewModel>>($"api/companies/{companyId:D}/operating/cycle-requests?take=20", ct);
    public Task<List<OperatingSnapshotViewModel>> ListSnapshotsAsync(Guid companyId, CancellationToken ct = default) => GetAsync<List<OperatingSnapshotViewModel>>($"api/companies/{companyId:D}/operating/snapshots?take=10", ct);
    public Task<CompanyOperatingConfigurationViewModel> UpdateConfigurationAsync(Guid companyId, UpdateCompanyOperatingConfigurationRequest request, CancellationToken ct = default) => SendAsync<CompanyOperatingConfigurationViewModel>(HttpMethod.Put, $"api/companies/{companyId:D}/operating/configuration", request, ct);
    public Task<CompanyGoalViewModel> CreateGoalAsync(Guid companyId, CreateCompanyGoalRequest request, CancellationToken ct = default) => PostAsync<CompanyGoalViewModel>($"api/companies/{companyId:D}/operating/goals", request, ct);
    public Task<CompanyGoalViewModel> ActivateGoalAsync(Guid companyId, Guid goalId, int expectedVersion, CancellationToken ct = default) => PostAsync<CompanyGoalViewModel>($"api/companies/{companyId:D}/operating/goals/{goalId:D}/activate?expectedVersion={expectedVersion}", new { }, ct);
    public Task<OperatingCycleViewModel> RunAsync(Guid companyId, CancellationToken ct = default) => PostAsync<OperatingCycleViewModel>($"api/companies/{companyId:D}/operating/cycles/recommend", new { triggerType = "manual" }, ct);
    public Task<OperatingCycleViewModel> ReviewAsync(Guid companyId, Guid planId, string decision, string? comment, CancellationToken ct = default) => PostAsync<OperatingCycleViewModel>($"api/companies/{companyId:D}/operating/plans/{planId:D}/review", new { decision, comment }, ct);
    public Task<OperatingCycleViewModel> CommitAsync(Guid companyId, Guid planId, CancellationToken ct = default) => PostAsync<OperatingCycleViewModel>($"api/companies/{companyId:D}/operating/plans/{planId:D}/commit", new { }, ct);
    public Task<CompanyOperatingConfigurationViewModel> PauseAsync(Guid companyId, int expectedVersion, string reason, CancellationToken ct = default) => PostAsync<CompanyOperatingConfigurationViewModel>($"api/companies/{companyId:D}/operating/pause", new { expectedVersion, reason }, ct);
    public Task<CompanyOperatingConfigurationViewModel> ResumeAsync(Guid companyId, int expectedVersion, CancellationToken ct = default) => PostAsync<CompanyOperatingConfigurationViewModel>($"api/companies/{companyId:D}/operating/resume", new { expectedVersion }, ct);
    public Task<CompanyOperatingConfigurationViewModel> EmergencyStopAsync(Guid companyId, int expectedVersion, string reason, CancellationToken ct = default) => PostAsync<CompanyOperatingConfigurationViewModel>($"api/companies/{companyId:D}/operating/emergency-stop", new { expectedVersion, reason }, ct);
    public Task<CompanyOperatingConfigurationViewModel> ClearEmergencyStopAsync(Guid companyId, int expectedVersion, CancellationToken ct = default) => PostAsync<CompanyOperatingConfigurationViewModel>($"api/companies/{companyId:D}/operating/emergency-stop/clear", new { expectedVersion }, ct);
    private async Task<T> GetAsync<T>(string uri, CancellationToken ct) { using var response = await http.GetAsync(uri, ct); await EnsureAsync(response, ct); return await response.Content.ReadFromJsonAsync<T>(Json, ct) ?? throw new InvalidOperationException("The server returned an empty response."); }
    private async Task<T> PostAsync<T>(string uri, object body, CancellationToken ct) { using var response = await http.PostAsJsonAsync(uri, body, Json, ct); await EnsureAsync(response, ct); return await response.Content.ReadFromJsonAsync<T>(Json, ct) ?? throw new InvalidOperationException("The server returned an empty response."); }
    private async Task<T> SendAsync<T>(HttpMethod method, string uri, object body, CancellationToken ct) { using var request = new HttpRequestMessage(method, uri) { Content = JsonContent.Create(body, options: Json) }; using var response = await http.SendAsync(request, ct); await EnsureAsync(response, ct); return await response.Content.ReadFromJsonAsync<T>(Json, ct) ?? throw new InvalidOperationException("The server returned an empty response."); }
    private static async Task EnsureAsync(HttpResponseMessage response, CancellationToken ct) { if (response.IsSuccessStatusCode) return; var problem = await response.Content.ReadFromJsonAsync<ApiProblemResponse>(Json, ct); throw new InvalidOperationException(problem?.Detail ?? problem?.Title ?? "The request could not be completed."); }
}

public sealed class CompanyGoalViewModel { public Guid Id { get; set; } public string Name { get; set; } = ""; public string Outcome { get; set; } = ""; public string Status { get; set; } = ""; public string Priority { get; set; } = ""; public string? MetricKey { get; set; } public string? MetricUnit { get; set; } public decimal? BaselineValue { get; set; } public decimal? TargetValue { get; set; } public DateTime StartUtc { get; set; } public DateTime TargetUtc { get; set; } public int Version { get; set; } }
public sealed class CompanyOperatingConfigurationViewModel { public Guid? CoordinatorAgentId { get; set; } public string AutonomyLevel { get; set; } = "recommend"; public bool IsPaused { get; set; } public string? PauseReason { get; set; } public bool EmergencyStopped { get; set; } public string? EmergencyStopReason { get; set; } public DateTime? EmergencyStoppedUtc { get; set; } public string Timezone { get; set; } = "UTC"; public int DailyCycleHour { get; set; } public int MinimumCycleIntervalMinutes { get; set; } public int MaximumCyclesPerDay { get; set; } public int MaximumInitiativesPerCycle { get; set; } public int MaximumTasksPerCycle { get; set; } public int MaximumCollaborators { get; set; } public int MaximumRuntimeSeconds { get; set; } public int MaximumModelCallsPerCycle { get; set; } public int MaximumToolCallsPerCycle { get; set; } public decimal? MaximumMonetaryBudgetPerCycle { get; set; } public int MaximumTasksPerDay { get; set; } public int MaximumModelCallsPerDay { get; set; } public int MaximumToolCallsPerDay { get; set; } public decimal? MaximumMonetaryBudgetPerDay { get; set; } public int Version { get; set; } }
public sealed class UpdateCompanyOperatingConfigurationRequest { public Guid? CoordinatorAgentId { get; set; } public string AutonomyLevel { get; set; } = "recommend"; public string Timezone { get; set; } = "UTC"; public int DailyCycleHour { get; set; } = 9; public int MinimumCycleIntervalMinutes { get; set; } = 60; public int MaximumCyclesPerDay { get; set; } = 4; public int MaximumInitiativesPerCycle { get; set; } = 8; public int MaximumTasksPerCycle { get; set; } = 16; public int MaximumCollaborators { get; set; } = 4; public int MaximumRuntimeSeconds { get; set; } = 300; public int MaximumModelCallsPerCycle { get; set; } = 4; public int MaximumToolCallsPerCycle { get; set; } = 20; public decimal? MaximumMonetaryBudgetPerCycle { get; set; } public int MaximumTasksPerDay { get; set; } = 48; public int MaximumModelCallsPerDay { get; set; } = 16; public int MaximumToolCallsPerDay { get; set; } = 80; public decimal? MaximumMonetaryBudgetPerDay { get; set; } public int ExpectedVersion { get; set; } }
public sealed class CreateCompanyGoalRequest { public string Name { get; set; } = ""; public string Outcome { get; set; } = ""; public string Priority { get; set; } = "normal"; public DateTime StartUtc { get; set; } = DateTime.UtcNow.Date; public DateTime TargetUtc { get; set; } = DateTime.UtcNow.Date.AddMonths(3); public string? MetricKey { get; set; } public string? MetricUnit { get; set; } public decimal? BaselineValue { get; set; } public decimal? TargetValue { get; set; } public Guid? OwnerAgentId { get; set; } }
public sealed class OperatingCycleViewModel { public Guid Id { get; set; } public string Status { get; set; } = ""; public string? FailureSummary { get; set; } public DateTime RequestedUtc { get; set; } public DateTime? CompletedUtc { get; set; } public int TasksCreated { get; set; } public int ModelCallsUsed { get; set; } public int ToolCallsUsed { get; set; } public decimal MonetaryBudgetUsed { get; set; } public List<OperatingPlanViewModel> Plans { get; set; } = []; }
public sealed class OperatingPlanViewModel { public Guid Id { get; set; } public string Status { get; set; } = ""; public string Objective { get; set; } = ""; public string RationaleSummary { get; set; } = ""; public int Version { get; set; } public Dictionary<string, JsonNode?> Uncertainty { get; set; } = []; public List<OperatingInitiativeViewModel> Initiatives { get; set; } = []; public List<OperatingValidationViewModel> ValidationResults { get; set; } = []; }
public sealed class OperatingInitiativeViewModel { public Guid Id { get; set; } public string Title { get; set; } = ""; public string DesiredOutcome { get; set; } = ""; public string Priority { get; set; } = ""; public string Status { get; set; } = ""; public string CompletionEvidence { get; set; } = ""; public Guid? OwnerAgentId { get; set; } public DateTime? TargetUtc { get; set; } public Guid? TaskId { get; set; } public Guid? WorkflowInstanceId { get; set; } public decimal? Budget { get; set; } public int Version { get; set; } }
public sealed class OperatingValidationViewModel { public string Outcome { get; set; } = ""; public string Explanation { get; set; } = ""; }
public sealed class OperatingDispatchViewModel { public Guid Id { get; set; } public Guid InitiativeId { get; set; } public Guid TaskId { get; set; } public string Kind { get; set; } = ""; public string Status { get; set; } = ""; public int AttemptCount { get; set; } public int MaxAttempts { get; set; } public DateTime? NextAttemptUtc { get; set; } public string? FailureSummary { get; set; } public DateTime UpdatedUtc { get; set; } }
public sealed class OperatingEventViewModel { public Guid Id { get; set; } public string EventType { get; set; } = ""; public string SourceType { get; set; } = ""; public string Materiality { get; set; } = ""; public string Status { get; set; } = ""; public string? SuppressionReason { get; set; } public DateTime ObservedUtc { get; set; } }
public sealed class OperatingCycleRequestViewModel { public Guid Id { get; set; } public string TriggerType { get; set; } = ""; public string Status { get; set; } = ""; public DateTime NotBeforeUtc { get; set; } public int AttemptCount { get; set; } public string? FailureSummary { get; set; } public DateTime CreatedUtc { get; set; } }
public sealed class OperatingSnapshotViewModel { public Guid Id { get; set; } public Guid CycleId { get; set; } public string SchemaVersion { get; set; } = ""; public int SourceCount { get; set; } public int DataGapCount { get; set; } public bool IsTruncated { get; set; } public DateTime CreatedUtc { get; set; } }
