namespace VirtualCompany.Web.Services;

public sealed partial class FinanceApiClient
{
    public Task<ComplianceCalendarResponse?> GetComplianceCalendarAsync(Guid companyId,DateOnly from,DateOnly to,CancellationToken ct=default)=>GetAsync<ComplianceCalendarResponse>(companyId,$"internal/companies/{companyId}/finance/accounting/compliance-obligations?from={from:yyyy-MM-dd}&to={to:yyyy-MM-dd}",false,ct);
    public Task<IReadOnlyList<ComplianceObligationResponse>> GenerateComplianceObligationsAsync(Guid companyId,string idempotencyKey,CancellationToken ct=default){EnsureOnlineMutation();return SendCompanyScopedAsync<object,IReadOnlyList<ComplianceObligationResponse>>(companyId,HttpMethod.Post,$"internal/companies/{companyId}/finance/accounting/compliance-obligations/generate",new{ownerUserId=Guid.Empty,idempotencyKey},ct);}
    public Task<ComplianceObligationResponse> TransitionComplianceObligationAsync(Guid companyId,Guid id,string action,long expectedVersion,string idempotencyKey,string? reason=null,CancellationToken ct=default){EnsureOnlineMutation();var endpoint=action is "approve" or "reject"?$"internal/companies/{companyId}/finance/accounting/compliance-obligations/{id:D}/decision":$"internal/companies/{companyId}/finance/accounting/compliance-obligations/{id:D}/transition";object body=action is "approve" or "reject"?new{approved=action=="approve",expectedVersion,idempotencyKey,reason}:new{action,expectedVersion,idempotencyKey,reason};return SendCompanyScopedAsync<object,ComplianceObligationResponse>(companyId,HttpMethod.Post,endpoint,body,ct);}
    public Task<ComplianceObligationResponse> RecordComplianceSubmissionAsync(Guid companyId,Guid id,string reference,string evidenceHash,long expectedVersion,string idempotencyKey,CancellationToken ct=default){EnsureOnlineMutation();return SendCompanyScopedAsync<object,ComplianceObligationResponse>(companyId,HttpMethod.Post,$"internal/companies/{companyId}/finance/accounting/compliance-obligations/{id:D}/manual-submission",new{reference,evidenceHash,expectedVersion,idempotencyKey},ct);}
    public Task<ComplianceObligationResponse> RecordComplianceAcknowledgementAsync(Guid companyId,Guid id,string kind,string reference,string evidenceHash,long expectedVersion,string idempotencyKey,CancellationToken ct=default){EnsureOnlineMutation();return SendCompanyScopedAsync<object,ComplianceObligationResponse>(companyId,HttpMethod.Post,$"internal/companies/{companyId}/finance/accounting/compliance-obligations/{id:D}/acknowledgements",new{kind,reference,evidenceHash,expectedVersion,idempotencyKey},ct);}
    public Task<ComplianceObligationResponse> ReviewComplianceEvidenceAsync(Guid companyId,Guid id,Guid evidenceId,bool accepted,long expectedVersion,string idempotencyKey,CancellationToken ct=default){EnsureOnlineMutation();return SendCompanyScopedAsync<object,ComplianceObligationResponse>(companyId,HttpMethod.Post,$"internal/companies/{companyId}/finance/accounting/compliance-obligations/{id:D}/submission-evidence/{evidenceId:D}/review",new{accepted,expectedVersion,idempotencyKey},ct);}
    public Task<int> GenerateComplianceRemindersAsync(Guid companyId,CancellationToken ct=default){EnsureOnlineMutation();return SendCompanyScopedAsync<object,int>(companyId,HttpMethod.Post,$"internal/companies/{companyId}/finance/accounting/compliance-obligations/reminders/generate",new{},ct);}
}
