namespace VirtualCompany.Web.Services;

public sealed partial class FinanceApiClient
{
    public Task<ComplianceCalendarResponse?> GetComplianceCalendarAsync(Guid companyId,DateOnly from,DateOnly to,CancellationToken ct=default)=>GetAsync<ComplianceCalendarResponse>(companyId,$"internal/companies/{companyId}/finance/accounting/compliance-obligations?from={from:yyyy-MM-dd}&to={to:yyyy-MM-dd}",false,ct);
    public Task<IReadOnlyList<ComplianceObligationResponse>> GenerateComplianceObligationsAsync(Guid companyId,string idempotencyKey,CancellationToken ct=default){EnsureOnlineMutation();return SendCompanyScopedAsync<object,IReadOnlyList<ComplianceObligationResponse>>(companyId,HttpMethod.Post,$"internal/companies/{companyId}/finance/accounting/compliance-obligations/generate",new{ownerUserId=Guid.Empty,idempotencyKey},ct);}
    public Task<ComplianceObligationResponse> TransitionComplianceObligationAsync(Guid companyId,Guid id,string action,long expectedVersion,string idempotencyKey,string? reason=null,CancellationToken ct=default){EnsureOnlineMutation();var endpoint=action is "approve" or "reject"?$"internal/companies/{companyId}/finance/accounting/compliance-obligations/{id:D}/decision":$"internal/companies/{companyId}/finance/accounting/compliance-obligations/{id:D}/transition";object body=action is "approve" or "reject"?new{approved=action=="approve",expectedVersion,idempotencyKey,reason}:new{action,expectedVersion,idempotencyKey,reason};return SendCompanyScopedAsync<object,ComplianceObligationResponse>(companyId,HttpMethod.Post,endpoint,body,ct);}
    public Task<ComplianceObligationResponse> RecordComplianceSubmissionAsync(Guid companyId,Guid id,string reference,string evidenceHash,long expectedVersion,string idempotencyKey,CancellationToken ct=default){EnsureOnlineMutation();return SendCompanyScopedAsync<object,ComplianceObligationResponse>(companyId,HttpMethod.Post,$"internal/companies/{companyId}/finance/accounting/compliance-obligations/{id:D}/manual-submission",new{reference,evidenceHash,expectedVersion,idempotencyKey},ct);}
    public Task<ComplianceObligationResponse> RecordComplianceAcknowledgementAsync(Guid companyId,Guid id,string kind,string reference,string evidenceHash,long expectedVersion,string idempotencyKey,CancellationToken ct=default){EnsureOnlineMutation();return SendCompanyScopedAsync<object,ComplianceObligationResponse>(companyId,HttpMethod.Post,$"internal/companies/{companyId}/finance/accounting/compliance-obligations/{id:D}/acknowledgements",new{kind,reference,evidenceHash,expectedVersion,idempotencyKey},ct);}
    public Task<ComplianceObligationResponse> ReviewComplianceEvidenceAsync(Guid companyId,Guid id,Guid evidenceId,bool accepted,long expectedVersion,string idempotencyKey,CancellationToken ct=default){EnsureOnlineMutation();return SendCompanyScopedAsync<object,ComplianceObligationResponse>(companyId,HttpMethod.Post,$"internal/companies/{companyId}/finance/accounting/compliance-obligations/{id:D}/submission-evidence/{evidenceId:D}/review",new{accepted,expectedVersion,idempotencyKey},ct);}
    public Task<int> GenerateComplianceRemindersAsync(Guid companyId,CancellationToken ct=default){EnsureOnlineMutation();return SendCompanyScopedAsync<object,int>(companyId,HttpMethod.Post,$"internal/companies/{companyId}/finance/accounting/compliance-obligations/reminders/generate",new{},ct);}
}

public sealed class ComplianceCalendarResponse { public Guid CompanyId{get;set;} public DateOnly From{get;set;} public DateOnly To{get;set;} public int OpenCount{get;set;} public int DueSoonCount{get;set;} public int OverdueCount{get;set;} public int AwaitingAuthorityCount{get;set;} public string SubmissionCapability{get;set;}=string.Empty; public List<ComplianceObligationResponse> Obligations{get;set;}=[]; }
public sealed class ComplianceObligationResponse { public Guid Id{get;set;} public string DefinitionKey{get;set;}=string.Empty; public string Title{get;set;}=string.Empty; public string Jurisdiction{get;set;}=string.Empty; public string PolicyPackKey{get;set;}=string.Empty; public string PolicyPackVersion{get;set;}=string.Empty; public string PolicyPackDefinitionHash{get;set;}=string.Empty; public string DueDateRule{get;set;}=string.Empty; public DateOnly DueDate{get;set;} public Guid OwnerUserId{get;set;} public string Status{get;set;}=string.Empty; public string SubmissionMode{get;set;}=string.Empty; public Guid VatFilingPeriodId{get;set;} public Guid? VatReturnId{get;set;} public Guid? AccountingCloseTaskId{get;set;} public Guid? CorrectionOfInstanceId{get;set;} public Guid? CorrectedByInstanceId{get;set;} public string SourceHash{get;set;}=string.Empty; public string? ExportReference{get;set;} public string? ExportChecksum{get;set;} public long Version{get;set;} public DateTime CreatedUtc{get;set;} public DateTime UpdatedUtc{get;set;} public string ComplianceNotice{get;set;}=string.Empty; public List<ComplianceRequirementResponse> Requirements{get;set;}=[]; public List<ComplianceHistoryResponse> History{get;set;}=[]; public List<ComplianceEvidenceResponse> SubmissionEvidence{get;set;}=[]; public List<ComplianceAcknowledgementResponse> Acknowledgements{get;set;}=[]; public List<ComplianceReminderResponse> Reminders{get;set;}=[]; public List<string> AllowedActions{get;set;}=[]; }
public sealed class ComplianceRequirementResponse { public string Kind{get;set;}=string.Empty; public string Label{get;set;}=string.Empty; public bool IsSatisfied{get;set;} public string? EvidenceReference{get;set;} }
public sealed class ComplianceHistoryResponse { public Guid Id{get;set;} public string Action{get;set;}=string.Empty; public string FromStatus{get;set;}=string.Empty; public string ToStatus{get;set;}=string.Empty; public Guid ActorUserId{get;set;} public string SourceHash{get;set;}=string.Empty; public string? Reason{get;set;} public DateTime OccurredUtc{get;set;} }
public sealed class ComplianceEvidenceResponse { public Guid Id{get;set;} public string Reference{get;set;}=string.Empty; public string ContentHash{get;set;}=string.Empty; public DateTime SubmittedUtc{get;set;} public string ReviewStatus{get;set;}=string.Empty; }
public sealed class ComplianceAcknowledgementResponse { public Guid Id{get;set;} public string Kind{get;set;}=string.Empty; public string Reference{get;set;}=string.Empty; public string ContentHash{get;set;}=string.Empty; public DateTime OccurredUtc{get;set;} }
public sealed class ComplianceReminderResponse { public Guid Id{get;set;} public string Kind{get;set;}=string.Empty; public int EscalationLevel{get;set;} public string Status{get;set;}=string.Empty; public DateTime CreatedUtc{get;set;} }
