using System.Net;using System.Net.Http.Json;using System.Text.Json;
namespace VirtualCompany.Web.Services;
public sealed class SalesPresentationRunApiClient(ICompanyApiTransport transport,bool offline,IApiProblemMessageResolver resolver)
{
 private static readonly JsonSerializerOptions Json=new(JsonSerializerDefaults.Web);private static string Root(Guid session)=>$"api/sales/meeting-sessions/{session:D}/presentation-run";
 public Task<SalesPresentationRunViewModel?>GetAsync(Guid company,Guid session,CancellationToken ct=default)=>Send<SalesPresentationRunViewModel>(company,HttpMethod.Get,Root(session),null,true,ct);
 public Task<SalesPresentationRunViewModel>ApplyAsync(Guid company,Guid session,ApplySalesPresentationPresetRequest request,CancellationToken ct=default)=>Required<SalesPresentationRunViewModel>(company,HttpMethod.Post,Root(session),JsonContent.Create(request,options:Json),ct);
 public Task<SalesPresentationRunViewModel>ApplyToInvitationAsync(Guid company,Guid invitation,ApplySalesPresentationPresetRequest request,CancellationToken ct=default)=>Required<SalesPresentationRunViewModel>(company,HttpMethod.Post,$"api/sales/meeting-invitations/{invitation:D}/presentation-run",JsonContent.Create(request,options:Json),ct);
 public Task<SalesPresentationRunViewModel>RetryAsync(Guid company,Guid session,Guid run,long version,CancellationToken ct=default)=>Required<SalesPresentationRunViewModel>(company,HttpMethod.Post,$"{Root(session)}/{run:D}/retry",JsonContent.Create(new{expectedVersion=version},options:Json),ct);
 public Task<SalesPresentationRunVersionComparisonViewModel?>CompareAsync(Guid company,Guid session,Guid run,Guid target,CancellationToken ct=default)=>Send<SalesPresentationRunVersionComparisonViewModel>(company,HttpMethod.Get,$"{Root(session)}/{run:D}/compare/{target:D}",null,true,ct);
 public Task<SalesPresentationPresetViewModel>SaveAsPresetAsync(Guid company,Guid session,Guid deck,string name,string? description,CancellationToken ct=default)=>Required<SalesPresentationPresetViewModel>(company,HttpMethod.Post,$"{Root(session)}/save-as-preset",JsonContent.Create(new{deckId=deck,name,description},options:Json),ct);
 private async Task<T>Required<T>(Guid c,HttpMethod m,string u,HttpContent? content,CancellationToken ct)=>await Send<T>(c,m,u,content,false,ct)??throw new SalesPresentationRunApiException("The presentation run API returned an empty response.");
 private async Task<T?>Send<T>(Guid c,HttpMethod m,string u,HttpContent? content,bool notFound,CancellationToken ct){if(offline)throw new SalesPresentationRunApiException("Presentation runs need the backend API.");try{using var response=await transport.SendAsync(c,m,u,content,ct);if(notFound&&response.StatusCode==HttpStatusCode.NotFound)return default;if(!response.IsSuccessStatusCode)throw await Error(response,ct);return await response.Content.ReadFromJsonAsync<T>(Json,ct);}catch(HttpRequestException){throw new SalesPresentationRunApiException("The presentation run service could not be reached.");}}
 private async Task<SalesPresentationRunApiException>Error(HttpResponseMessage response,CancellationToken ct){ApiProblemResponse? p=null;if(response.Content.Headers.ContentType?.MediaType is "application/json" or "application/problem+json")p=await response.Content.ReadFromJsonAsync<ApiProblemResponse>(Json,ct);var fallback=p?.Errors?.SelectMany(x=>x.Value).FirstOrDefault()??p?.Detail??p?.Title??"The request failed.";return new(resolver.Resolve(p,fallback),response.StatusCode,p?.Code);}
}
public sealed class SalesPresentationRunApiException(string message,HttpStatusCode? status=null,string? code=null):Exception(message){public HttpStatusCode? StatusCode{get;}=status;public string? Code{get;}=code;}
public sealed record ApplySalesPresentationPresetRequest(Guid? PresetId,Guid? PresetVersionId,Guid? PresenterAgentId,string? Goal,string? Audience,int? DurationMinutes,string? DemoScenario,string? Language,string? ControlMode,bool ReplaceActive,long? ExpectedActiveRunVersion);
public sealed record SalesPresentationRunArtifactViewModel(Guid Id,string Type,string Content,string Classification,string? SourceReference,Guid? PresetSlideId,int Order,Guid? AiRunId);
public sealed record SalesPresentationRunViewModel(Guid Id,Guid MeetingSessionId,Guid PresetId,string PresetName,Guid PresetVersionId,int PresetVersionNumber,Guid PresenterAgentId,string PresenterName,string Goal,string Audience,int DurationMinutes,string? DemoScenario,string Language,string ControlMode,bool GoalOverridden,bool AudienceOverridden,bool DurationOverridden,bool DemoScenarioOverridden,bool PresenterOverridden,string PreparationStatus,IReadOnlyList<string> ReadinessBlockers,bool CanRetry,string? FailureCode,string? FailureSummary,Guid? CompatibilityDeckId,bool IsActive,int? NewerPublishedVersion,long ConcurrencyVersion,IReadOnlyList<SalesPresentationRunArtifactViewModel> Artifacts);
public sealed record SalesPresentationRunVersionChangeViewModel(string Field,string CurrentValue,string NewValue,bool OverridePreserved,bool Incompatible);public sealed record SalesPresentationRunVersionComparisonViewModel(Guid RunId,Guid CurrentVersionId,int CurrentVersion,Guid TargetVersionId,int TargetVersion,IReadOnlyList<SalesPresentationRunVersionChangeViewModel> Changes,bool CanUpdate,IReadOnlyList<string> Blockers);
