using VirtualCompany.Application.Support;
using Xunit;
namespace VirtualCompany.SupportGrounding.Tests;

public sealed class SupportCapacityCalculationTests
{
    private static readonly DateTime Now=new(2026,10,5,12,0,0,DateTimeKind.Utc);
    private static SupportBusinessCalendarDto Calendar=>new("Europe/Stockholm",new(8,0),new(17,0),[DayOfWeek.Monday,DayOfWeek.Tuesday,DayOfWeek.Wednesday,DayOfWeek.Thursday,DayOfWeek.Friday],[new(2026,10,12)]);
    private static SupportQualityReport Report(SupportBusinessCalendarDto? calendar=null)=>new(Guid.NewGuid(),new(2026,9),SupportCapacityCalculation.Version,Now,Now,new(new(2026,9,1),new(2026,10,1),new(2026,10,1),"Europe/Stockholm"),calendar??Calendar,new(3,2,1,50,2,1440,60,2,4440),new(0,0,0,null,0,null,null,0,null),[],[],[],true,"Recorded sources","Cohort definition",new string('a',64),"Accountable reviewer");
    private static SupportCapacityAssumptions Input=>new(2026,10,20,5,30,1,4,80,60,"Explicit workload assumptions.");
    [Fact]public void Capacity_uses_holidays_distinct_observed_workload_and_exact_decimals(){var r=SupportCapacityCalculation.Calculate(Report(),Input,Now);Assert.Equal(21,r.BusinessDays);Assert.Equal(3,r.ObservedArrivals);Assert.Equal(20,r.AssumedArrivals);Assert.Equal(12.5m,r.RequiredHours);Assert.Equal(67.2m,r.AvailableHours);Assert.Equal(134,r.CaseCapacity);Assert.Equal(.19m,r.RequiredPeople);}
    [Fact]public void Zero_staff_and_no_business_days_are_explicit_shortfalls_not_service_promises(){var r=SupportCapacityCalculation.Calculate(Report(),Input with{AvailablePeople=0},Now);Assert.Equal(12.5m,r.ShortfallHours);Assert.Equal(0,r.CaseCapacity);var c=Calendar with{Holidays=Enumerable.Range(1,31).Select(d=>new DateOnly(2026,10,d)).ToArray()};r=SupportCapacityCalculation.Calculate(Report(c),Input,Now);Assert.Equal(0,r.BusinessDays);Assert.Null(r.RequiredPeople);Assert.Contains("no queue distribution",r.Limits);}
    [Fact]public void Invalid_precision_calendar_bounds_and_incomplete_sources_are_rejected(){foreach(var a in new[]{Input with{HandlingMinutes=30.001m},Input with{HoursPerBusinessDay=10},Input with{ExpectedArrivals=-1},Input with{TargetMonth=9},Input with{TargetYear=2028},Input with{UtilizationPercent=0}})Assert.Throws<ArgumentException>(()=>SupportCapacityCalculation.Calculate(Report(),a,Now));Assert.Throws<ArgumentException>(()=>SupportCapacityCalculation.Calculate(Report() with{CompleteSourceCoverage=false},Input,Now));}
    [Fact]public void Business_time_replay_excludes_weekend_holiday_and_follows_timezone_dst(){var c=Calendar;Assert.Equal(60,SupportBusinessTime.Minutes(new(2026,9,5,8,0,0,DateTimeKind.Utc),new(2026,9,7,7,0,0,DateTimeKind.Utc),c));Assert.Equal(0,SupportBusinessTime.Minutes(new(2026,10,12,7,0,0,DateTimeKind.Utc),new(2026,10,12,9,0,0,DateTimeKind.Utc),c));Assert.Equal(180,SupportBusinessTime.Minutes(new(2026,10,23,14,0,0,DateTimeKind.Utc),new(2026,10,26,9,0,0,DateTimeKind.Utc),c));}
    [Fact]public void Capacity_overflow_and_inverted_business_time_are_validation_failures(){var c=Calendar with{WorkdayStart=new(0,0),WorkdayEnd=new(23,59)};Assert.Throws<ArgumentException>(()=>SupportCapacityCalculation.Calculate(Report(c),Input with{HandlingMinutes=.01m,AvailablePeople=1000,HoursPerBusinessDay=23.98m,UtilizationPercent=100},Now));Assert.Throws<ArgumentException>(()=>SupportBusinessTime.Minutes(Now,Now.AddMinutes(-1),Calendar));}
}
